// Diogo's academy — AI-assisted development, pitched at a senior frontend dev
// who wants to out-skill the market on practical AI tooling (not ML theory).
// ~20 seed questions per topic; `npm run quiz:regen` tops topics up to 50 and
// the weekly `npm run quiz:review` (sonnet) refreshes/extends them as AI moves.
import type { QuizQuestion } from '../types'

const AT = '2026-07-18T00:00:00.000Z'

const choice = (
  id: string,
  topicId: string,
  prompt: string,
  choices: string[],
  answer: string,
  opts: Partial<QuizQuestion> = {},
): QuizQuestion => ({
  id,
  topicId,
  type: 'choice',
  prompt,
  choices,
  answer,
  weight: 2,
  points: 8,
  status: 'active',
  createdAt: AT,
  ...opts,
})

// --- AI in Software Dev ----------------------------------------------------
const ASD = 'ai-software-dev'

const AI_SOFTWARE_DEV: QuizQuestion[] = [
  choice('asd-01', ASD, 'What is a "token" for an LLM?', [
    'One full word, always',
    'A chunk of text, roughly ¾ of a word / ~4 characters in English',
    'One line of code',
    'A unit of GPU memory',
  ], 'A chunk of text, roughly ¾ of a word / ~4 characters in English', {
    emoji: '🪙',
    funFact: 'Everything — your prompt, the files it reads, its own answer — is billed in tokens. Code is token-dense: braces, indentation and long identifiers all count.',
  }),
  choice('asd-02', ASD, 'The "context window" of a model is…', [
    'How long it will keep responding before timing out',
    'The maximum tokens it can consider at once — its working memory',
    'The number of files it can edit',
    'The size of its training data',
  ], 'The maximum tokens it can consider at once — its working memory', {
    emoji: '🪟',
    funFact: 'When the window fills, something must be dropped or summarized — that\'s why long sessions "forget" early instructions.',
  }),
  choice('asd-03', ASD, 'Cheapest fix when you repeatedly send the same big system prompt + docs to an API?', [
    'Lower the temperature',
    'Prompt caching — reuse the identical prefix at a fraction of the cost',
    'Switch to streaming',
    'Send it as an attachment',
  ], 'Prompt caching — reuse the identical prefix at a fraction of the cost', {
    emoji: '💸',
    funFact: 'On the Claude API, cached prompt reads cost ~10% of normal input tokens. Structure prompts so the stable part comes first and stays byte-identical.',
  }),
  choice('asd-04', ASD, 'RAG improves answers by…', [
    'Retraining the model on your data every night',
    'Retrieving relevant documents at question-time and stuffing them into the prompt',
    'Running the model twice and comparing',
    'Blocking hallucinated URLs',
  ], 'Retrieving relevant documents at question-time and stuffing them into the prompt', {
    emoji: '📚',
    funFact: 'RAG = fetch first, then generate. The model never "learns" your docs — it just reads the excerpts you retrieve for each question.',
  }),
  choice('asd-05', ASD, 'MCP (Model Context Protocol) standardizes…', [
    'How models are fine-tuned',
    'How AI apps connect models to external tools and data sources',
    'GPU scheduling in the cloud',
    'Prompt formatting between vendors',
  ], 'How AI apps connect models to external tools and data sources', {
    emoji: '🔌',
    funFact: 'Think "USB for AI tools": one MCP server (say, your Postgres or Jira) can plug into Claude, Copilot, Cursor — any MCP client.',
  }),
  choice('asd-06', ASD, 'The system prompt is…', [
    'The user\'s first message',
    'Standing instructions that frame the whole conversation (role, rules, style)',
    'A prompt generated by the OS',
    'The model\'s hidden chain of thought',
  ], 'Standing instructions that frame the whole conversation (role, rules, style)', {
    emoji: '📜',
    funFact: 'Tools like Claude Code and Copilot build a big system prompt for you — your CLAUDE.md / custom instructions get injected into it.',
  }),
  choice('asd-07', ASD, 'Raising temperature makes output…', [
    'More random/creative',
    'More factual',
    'Faster',
    'Cheaper',
  ], 'More random/creative', {
    emoji: '🌡️',
    funFact: 'For code you usually want low randomness — deterministic, boring, correct. Save high temperature for brainstorming.',
  }),
  choice('asd-08', ASD, 'Best everyday defense against AI hallucinations in code?', [
    'Ask the model if it is sure',
    'Verification you control: run tests, typecheck, execute the code',
    'Use a bigger model and trust it',
    'Keep prompts under 100 tokens',
  ], 'Verification you control: run tests, typecheck, execute the code', {
    emoji: '🧪',
    funFact: 'A feedback loop (tests, compiler, linter) turns "sounds right" into "provably works" — it\'s THE difference between vibe coding and engineering with AI.',
  }),
  choice('asd-09', ASD, 'What makes an "agent" different from a single completion?', [
    'It uses a bigger model',
    'It loops: takes actions with tools, observes results, and keeps going until the goal is done',
    'It always runs in the cloud',
    'It writes longer answers',
  ], 'It loops: takes actions with tools, observes results, and keeps going until the goal is done', {
    emoji: '🤖',
    funFact: 'Agent = model + tools + loop. The "magic" is mostly the loop reading real feedback (test output, file contents) each turn.',
  }),
  choice('asd-10', ASD, '"Orchestration" in AI dev usually means…', [
    'Streaming tokens to the UI in order',
    'Coordinating multiple agents/steps — e.g. a planner delegating to parallel workers, then merging results',
    'Renting several GPUs',
    'Chaining prompts in one chat window',
  ], 'Coordinating multiple agents/steps — e.g. a planner delegating to parallel workers, then merging results', {
    emoji: '🎼',
    funFact: 'Classic pattern: one orchestrator plans and fans work out to subagents (each with a fresh context window), then reviews what comes back. That\'s how big refactors stay coherent.',
  }),
  choice('asd-11', ASD, 'Running an AI coding tool "headless" means…', [
    'Without a monitor plugged in',
    'Non-interactively — invoked from scripts/CI with a prompt, output captured programmatically',
    'With the safety filters off',
    'Without internet',
  ], 'Non-interactively — invoked from scripts/CI with a prompt, output captured programmatically', {
    emoji: '🕶️',
    funFact: 'Headless mode (e.g. `claude -p "…"`) turns the assistant into a build step: nightly triage, auto-review, changelog writing — no human at the keyboard.',
  }),
  {
    id: 'asd-12',
    topicId: ASD,
    type: 'order',
    prompt: 'Order the steps of a solid agentic coding workflow:',
    emoji: '🗺️',
    sequence: ['Explore the codebase', 'Write a plan', 'Implement the changes', 'Verify with tests'],
    weight: 2,
    points: 10,
    status: 'active',
    createdAt: AT,
    funFact: 'Explore → plan → code → verify beats "just code it" because the model commits to an approach before touching files — fewer dead ends, fewer tokens.',
  },
  choice('asd-13', ASD, 'Why paste an error message verbatim instead of paraphrasing it?', [
    'It is faster to type',
    'Exact strings (codes, file:line, stack frames) let the model match the real cause instead of guessing',
    'Paraphrasing is against the ToS',
    'Models can\'t read paraphrases',
  ], 'Exact strings (codes, file:line, stack frames) let the model match the real cause instead of guessing', {
    emoji: '📋',
    funFact: 'Same rule as a good bug report. Bonus: include what you already tried, so the model doesn\'t redo it.',
  }),
  choice('asd-14', ASD, 'Asking the model to "think step by step" or giving it a scratchpad mainly helps because…', [
    'It slows the API down so you read along',
    'Intermediate reasoning improves accuracy on multi-step problems',
    'It reduces token usage',
    'It disables hallucinations',
  ], 'Intermediate reasoning improves accuracy on multi-step problems', {
    emoji: '🧠',
    funFact: 'Modern tools expose this as "extended thinking" / reasoning effort settings — more thinking budget for hard problems, less for trivial ones.',
  }),
  {
    id: 'asd-15',
    topicId: ASD,
    type: 'match',
    prompt: 'Match each concept to what it does:',
    emoji: '🔗',
    pairs: [
      { left: 'RAG', right: 'Fetch relevant docs into the prompt' },
      { left: 'MCP', right: 'Standard plug for external tools' },
      { left: 'Agent', right: 'Tool-using loop until the goal is done' },
      { left: 'Prompt caching', right: 'Reuse an identical prefix cheaply' },
    ],
    weight: 2,
    points: 10,
    status: 'active',
    createdAt: AT,
    funFact: 'These four cover most "AI architecture" conversations in interviews: grounding, integration, autonomy, and cost.',
  },
  choice('asd-16', ASD, 'A long chat session slowly gets dumber. Most likely cause?', [
    'The model gets tired',
    'The context window is filling with stale history that crowds out what matters',
    'Your API key is throttled',
    'Temperature drifts upward',
  ], 'The context window is filling with stale history that crowds out what matters', {
    emoji: '🥴',
    funFact: 'Fix: summarize state and start fresh (e.g. /compact), or scope sessions to one task each. Context is a budget — spend it on the current problem.',
  }),
  choice('asd-17', ASD, 'Which prompt gets the best result from a coding agent?', [
    '"Fix the bug"',
    '"Make the app better"',
    '"Login fails with 401 after token refresh — see src/auth/refresh.ts; write a failing test first, then fix, keep the public API unchanged"',
    '"You are the world\'s best programmer. Fix everything."',
  ], '"Login fails with 401 after token refresh — see src/auth/refresh.ts; write a failing test first, then fix, keep the public API unchanged"', {
    emoji: '🎯',
    funFact: 'Files, symptoms, constraints, and a definition of done. Specificity is the cheapest performance upgrade there is.',
  }),
  choice('asd-18', ASD, 'On most LLM APIs, which tokens usually cost MORE?', [
    'Input tokens',
    'Output tokens',
    'They always cost the same',
    'Cached tokens',
  ], 'Output tokens', {
    emoji: '🧾',
    funFact: 'Output is typically several times the input price. Asking for terse diffs instead of full rewritten files is a real cost lever.',
  }),
  choice('asd-19', ASD, 'Senior-level habit when an AI writes a big chunk of your code?', [
    'Merge it if the demo works',
    'Review the diff like a junior\'s PR — read every line you\'ll own in prod',
    'Regenerate it three times and pick the longest',
    'Add a comment saying AI wrote it',
  ], 'Review the diff like a junior\'s PR — read every line you\'ll own in prod', {
    emoji: '🔍',
    funFact: 'The market gap isn\'t "can use AI" — it\'s "can supervise AI": tight specs, real review, and verification. That\'s the skill that stays valuable.',
  }),
  {
    id: 'asd-20',
    topicId: ASD,
    type: 'write',
    prompt: 'What does the R in RAG stand for? (one word)',
    emoji: '✍️',
    accept: ['Retrieval', 'retrieval augmented', 'retrieval-augmented'],
    weight: 2,
    points: 8,
    status: 'active',
    createdAt: AT,
    funFact: 'Retrieval-Augmented Generation — retrieve first, generate second.',
  },
]

// --- GitHub Copilot --------------------------------------------------------
const COP = 'copilot-ai'

const COPILOT: QuizQuestion[] = [
  choice('cop-01', COP, 'Which key accepts an inline Copilot suggestion in VS Code?', ['Enter', 'Tab', 'Ctrl+Space', 'F2'], 'Tab', {
    emoji: '⌨️',
    weight: 1,
    points: 5,
    funFact: 'And you can accept just the next word with Cmd+→ — handy when only the start of the ghost text is right.',
  }),
  choice('cop-02', COP, 'Which slash command asks Copilot Chat to generate unit tests?', ['/unit', '/tests', '/spec', '/check'], '/tests', {
    emoji: '🧪',
    funFact: 'Select the function first — slash commands act on your selection/current file context.',
  }),
  choice('cop-03', COP, '/explain is for…', [
    'Explaining the selected code in plain language',
    'Explaining why Copilot is disabled',
    'Documenting your repo',
    'Printing the model\'s settings',
  ], 'Explaining the selected code in plain language', {
    emoji: '🧑‍🏫',
    funFact: 'Great on unfamiliar regex, legacy code, or a teammate\'s clever one-liner before you touch it.',
  }),
  choice('cop-04', COP, '/fix does what?', [
    'Reformats the file',
    'Proposes a repair for the selected/problematic code',
    'Fixes merge conflicts automatically',
    'Rolls back the last commit',
  ], 'Proposes a repair for the selected/problematic code', {
    emoji: '🔧',
    funFact: 'Pair it with the exact error: select the code, paste the message, then /fix — context beats magic.',
  }),
  choice('cop-05', COP, 'Which chat participant answers questions about your WHOLE codebase?', ['@vscode', '@terminal', '@workspace', '@github'], '@workspace', {
    emoji: '🗂️',
    funFact: '@workspace indexes your project so "where is auth handled?" gets a real answer with file references.',
  }),
  choice('cop-06', COP, '@terminal is the participant that…', [
    'Runs your unit tests',
    'Helps with shell commands and explains terminal output/errors',
    'Opens a remote SSH session',
    'Controls VS Code settings',
  ], 'Helps with shell commands and explains terminal output/errors', {
    emoji: '💻',
    funFact: 'There\'s also @vscode for editor-settings questions ("how do I enable format on save?").',
  }),
  choice('cop-07', COP, 'Repo-wide custom instructions for Copilot live in…', [
    '.github/copilot-instructions.md',
    'copilot.config.json',
    '.vscode/copilot.txt',
    'README.md',
  ], '.github/copilot-instructions.md', {
    emoji: '📋',
    funFact: 'Put stack, conventions and "always/never" rules there — every chat request in the repo gets them silently. The Copilot equivalent of CLAUDE.md.',
  }),
  choice('cop-08', COP, 'How do you pin a specific file into a Copilot Chat question?', [
    'Type #file (or drag the file into chat)',
    'Prefix with //',
    'Use /attach',
    'You can\'t — it only sees the open editor',
  ], 'Type #file (or drag the file into chat)', {
    emoji: '📎',
    funFact: 'Context variables like #file and #selection let you hand-pick context instead of hoping Copilot guesses the right files.',
  }),
  choice('cop-09', COP, 'Copilot "agent mode" in VS Code can…', [
    'Only autocomplete single lines',
    'Autonomously edit multiple files, run terminal commands, and iterate on errors until the task is done',
    'Only work on GitHub.com',
    'Train on your repo overnight',
  ], 'Autonomously edit multiple files, run terminal commands, and iterate on errors until the task is done', {
    emoji: '🤖',
    funFact: 'Ask mode answers, edit mode changes files you picked, agent mode picks files itself and loops on failures. Pick the least autonomy that does the job.',
  }),
  choice('cop-10', COP, 'Copilot Edits differs from plain Chat because it…', [
    'Uses a different login',
    'Runs a multi-file edit session with reviewable per-file changes you accept/discard',
    'Is only for Markdown',
    'Cannot use context',
  ], 'Runs a multi-file edit session with reviewable per-file changes you accept/discard', {
    emoji: '📝',
    funFact: 'You stay the reviewer: each touched file shows its diff and you keep or reject changes one by one.',
  }),
  choice('cop-11', COP, 'The model picker in Copilot Chat lets you…', [
    'Choose which LLM answers (GPT, Claude, Gemini…) per conversation',
    'Pick which repo to index',
    'Change your subscription tier',
    'Select the programming language',
  ], 'Choose which LLM answers (GPT, Claude, Gemini…) per conversation', {
    emoji: '🎚️',
    funFact: 'Different models, different strengths (and premium-request costs). Trying the same hard prompt on two models is a legit debugging technique.',
  }),
  choice('cop-12', COP, '"Next edit suggestions" (NES) predict…', [
    'Your next keystroke',
    'Where in the file your NEXT related change should happen, and propose it',
    'The next file you will open',
    'Your sprint velocity',
  ], 'Where in the file your NEXT related change should happen, and propose it', {
    emoji: '🔮',
    weight: 1,
    points: 5,
    funFact: 'Rename a variable or change a signature and NES walks you through the ripple effects — Tab, Tab, Tab.',
  }),
  choice('cop-13', COP, 'Copilot code review can…', [
    'Merge PRs automatically',
    'Review a selection or whole pull request and leave suggested-change comments',
    'Only check formatting',
    'Replace CI',
  ], 'Review a selection or whole pull request and leave suggested-change comments', {
    emoji: '🔍',
    funFact: 'On GitHub.com you can request Copilot as a PR reviewer like a teammate. Treat its comments like a sharp junior\'s: often right, always verify.',
  }),
  choice('cop-14', COP, 'In the terminal, `gh copilot suggest` …', [
    'Suggests a shell command from a natural-language description',
    'Suggests repo names',
    'Opens Copilot Chat in the browser',
    'Updates the gh CLI',
  ], 'Suggests a shell command from a natural-language description', {
    emoji: '⌨️',
    weight: 1,
    points: 5,
    funFact: '`gh copilot explain "tar -xzvf …"` does the reverse — explains a scary command before you run it.',
  }),
  choice('cop-15', COP, 'The sparkle icon in the Source Control box generates…', [
    'A .gitignore',
    'A commit message from your staged changes',
    'A release note',
    'A code owner file',
  ], 'A commit message from your staged changes', {
    emoji: '✨',
    weight: 1,
    points: 5,
    funFact: 'It reads the actual diff — usually a better summary than "fix stuff". Edit before committing, it\'s a draft.',
  }),
  choice('cop-16', COP, 'Biggest lever to improve Copilot\'s INLINE suggestions?', [
    'Typing faster',
    'Good context: open related files, meaningful names, a comment stating intent',
    'Restarting VS Code hourly',
    'Using shorter variable names',
  ], 'Good context: open related files, meaningful names, a comment stating intent', {
    emoji: '🧲',
    funFact: 'Inline Copilot mostly sees your open tabs. Open the type definitions and a similar existing component before writing a new one.',
  }),
  {
    id: 'cop-17',
    topicId: COP,
    type: 'match',
    prompt: 'Match the slash command to its job:',
    emoji: '🔗',
    pairs: [
      { left: '/tests', right: 'Generate unit tests' },
      { left: '/fix', right: 'Propose a repair' },
      { left: '/explain', right: 'Teach me this code' },
      { left: '/doc', right: 'Write documentation comments' },
    ],
    weight: 2,
    points: 10,
    status: 'active',
    createdAt: AT,
    funFact: 'Slash commands are just packaged prompts — you can create your own as reusable prompt files.',
  },
  {
    id: 'cop-18',
    topicId: COP,
    type: 'write',
    prompt: 'Type the filename (just the file, not the folder) for repo-wide Copilot custom instructions:',
    emoji: '✍️',
    accept: ['copilot-instructions.md', 'copilot instructions md', '.github/copilot-instructions.md'],
    weight: 2,
    points: 8,
    status: 'active',
    createdAt: AT,
    funFact: 'Full path: .github/copilot-instructions.md. Keep it short and rule-like; giant essays dilute the signal.',
  },
  choice('cop-19', COP, 'The Copilot "coding agent" on GitHub.com works by…', [
    'Pair-programming over video',
    'Being assigned an issue/task and opening a draft PR with the changes for your review',
    'Auto-merging Dependabot PRs',
    'Editing directly on main',
  ], 'Being assigned an issue/task and opening a draft PR with the changes for your review', {
    emoji: '🐙',
    funFact: 'Delegate the well-specified, boring issues; keep the ambiguous ones. Writing a crisp issue IS the prompt engineering.',
  }),
  choice('cop-20', COP, 'Content exclusions in Copilot settings are for…', [
    'Muting chat notifications',
    'Blocking Copilot from reading specified files/paths (secrets, licensed code)',
    'Hiding suggestions in comments',
    'Disabling telemetry',
  ], 'Blocking Copilot from reading specified files/paths (secrets, licensed code)', {
    emoji: '🙈',
    funFact: 'Admins set these org-wide. Know this one for work: it\'s the standard answer to "but what about our proprietary code?"',
  }),
]

// --- Claude Code -----------------------------------------------------------
const CC = 'claude-code-ai'

const CLAUDE_CODE: QuizQuestion[] = [
  choice('cc-01', CC, 'What is CLAUDE.md?', [
    'The changelog Claude writes',
    'A project file auto-loaded into context: conventions, commands, rules for the repo',
    'Claude\'s license file',
    'A generated API doc',
  ], 'A project file auto-loaded into context: conventions, commands, rules for the repo', {
    emoji: '📖',
    funFact: 'It\'s persistent memory: build commands, style rules, "never touch X". Keep it lean — every line costs tokens in EVERY session.',
  }),
  choice('cc-02', CC, 'Which command bootstraps a CLAUDE.md by analyzing your codebase?', ['/setup', '/init', '/start', '/learn'], '/init', {
    emoji: '🚀',
    funFact: 'Run /init once in a new repo, then edit the result. Add hard-won corrections over time (or ask Claude to remember them).',
  }),
  choice('cc-03', CC, 'Plan mode is for…', [
    'Scheduling cron jobs',
    'Letting Claude research and propose a plan you approve BEFORE it edits anything',
    'Formatting the sprint board',
    'Slowing down output for reading',
  ], 'Letting Claude research and propose a plan you approve BEFORE it edits anything', {
    emoji: '🗺️',
    funFact: 'Shift+Tab cycles modes. For multi-file changes, reviewing a plan is far cheaper than reviewing a wrong implementation.',
  }),
  choice('cc-04', CC, 'Subagents (the Task/Agent tool) are valuable because they…', [
    'Are free of charge',
    'Run with their OWN context windows — exploration happens there and only conclusions return',
    'Can access the internet when the main agent can\'t',
    'Always use a bigger model',
  ], 'Run with their OWN context windows — exploration happens there and only conclusions return', {
    emoji: '🕵️',
    funFact: 'Fan out three subagents to search a big repo in parallel; your main context stays clean for the actual change. This is everyday "orchestration".',
  }),
  choice('cc-05', CC, 'Hooks in Claude Code let you…', [
    'Style the terminal UI',
    'Run your own shell commands on events (after edits, before tool calls) — e.g. auto-format or block dangerous commands',
    'Subscribe to Anthropic newsletters',
    'Add Git hooks to the repo',
  ], 'Run your own shell commands on events (after edits, before tool calls) — e.g. auto-format or block dangerous commands', {
    emoji: '🪝',
    funFact: 'A PostToolUse hook running Prettier after every edit means Claude literally cannot leave unformatted code behind — determinism beats asking nicely.',
  }),
  choice('cc-06', CC, 'You connect Claude Code to external tools/data (DBs, browsers, Jira…) via…', [
    'Browser extensions',
    'MCP servers (e.g. `claude mcp add`)',
    'Copy-pasting JSON',
    'A Zapier account',
  ], 'MCP servers (e.g. `claude mcp add`)', {
    emoji: '🔌',
    funFact: 'Claude Code is an MCP client; it can also expose itself as a server. Same protocol Copilot and Cursor speak.',
  }),
  choice('cc-07', CC, 'Headless Claude Code for scripts/CI is…', [
    'claude --quiet',
    'claude -p "your prompt"',
    'claude --no-ui',
    'claude run',
  ], 'claude -p "your prompt"', {
    emoji: '🕶️',
    funFact: 'Add --output-format json (or stream-json) to parse results programmatically. Your repo\'s asset-optimization npm script already works this way!',
  }),
  choice('cc-08', CC, '/compact vs /clear — what\'s the difference?', [
    'They are aliases',
    '/compact summarizes the conversation to free tokens; /clear wipes it completely',
    '/compact minifies code; /clear deletes files',
    '/clear is only for errors',
  ], '/compact summarizes the conversation to free tokens; /clear wipes it completely', {
    emoji: '🧹',
    funFact: 'Between unrelated tasks, /clear is usually better than /compact: a fresh context beats a summary of things that no longer matter.',
  }),
  choice('cc-09', CC, 'To reopen yesterday\'s session with its full context you use…', [
    '--continue (or --resume to pick from a list)',
    '--history',
    '--undo',
    'It\'s impossible',
  ], '--continue (or --resume to pick from a list)', {
    emoji: '⏪',
    weight: 1,
    points: 5,
    funFact: '`claude --continue` resumes the most recent conversation in that directory — context, decisions and all.',
  }),
  choice('cc-10', CC, 'Tired of approving `npm test` every time? The right fix is…', [
    'Always run with --dangerously-skip-permissions',
    'An allowlist in .claude/settings.json permissions (e.g. Bash(npm test:*))',
    'Typing "yes" faster',
    'Disabling the Bash tool',
  ], 'An allowlist in .claude/settings.json permissions (e.g. Bash(npm test:*))', {
    emoji: '🛂',
    funFact: 'Allow the safe, frequent commands; keep prompts for the destructive ones. Skip-permissions belongs in throwaway containers only.',
  }),
  choice('cc-11', CC, 'Custom slash commands / skills are…', [
    'Paid plugins',
    'Markdown files of instructions (.claude/commands, skills) you invoke as /name',
    'Python scripts in the cloud',
    'Aliases for git commands',
  ], 'Markdown files of instructions (.claude/commands, skills) you invoke as /name', {
    emoji: '📦',
    funFact: 'Team-shared prompts in git: /deploy-check, /review-checklist… Write once, everyone (and every future session) benefits.',
  }),
  choice('cc-12', CC, 'Which habit BURNS the most tokens for no gain?', [
    'Pointing Claude at the exact files that matter',
    'Letting it re-explore the whole repo every session while CLAUDE.md holds an essay',
    'Using /clear between tasks',
    'Scoping each session to one task',
  ], 'Letting it re-explore the whole repo every session while CLAUDE.md holds an essay', {
    emoji: '🔥',
    funFact: 'Token diet: name files/dirs in your prompt, keep CLAUDE.md tight, /clear often, and let subagents do the searching.',
  }),
  {
    id: 'cc-13',
    topicId: CC,
    type: 'order',
    prompt: 'Order Anthropic\'s recommended workflow for a non-trivial change:',
    emoji: '🧭',
    sequence: ['Explore the relevant code', 'Plan (and approve the plan)', 'Implement', 'Verify & commit'],
    weight: 2,
    points: 10,
    status: 'active',
    createdAt: AT,
    funFact: 'Same shape as the general agentic loop — Claude Code just gives each phase a first-class mode.',
  },
  choice('cc-14', CC, 'Running several Claude sessions on one repo without them fighting is best done with…', [
    'git worktrees — one directory + branch per session',
    'Committing after every message',
    'Turning off git',
    'One session per monitor',
  ], 'git worktrees — one directory + branch per session', {
    emoji: '🌳',
    funFact: 'Worktrees share history but isolate working files: one Claude fixes a bug while another builds a feature, zero stepping on toes.',
  }),
  choice('cc-15', CC, 'Smart model strategy inside Claude Code?', [
    'Always the biggest model for everything',
    'Match the model to the task — big for planning/hard problems, faster/cheaper for routine edits',
    'Always the cheapest model',
    'Alternate randomly',
  ], 'Match the model to the task — big for planning/hard problems, faster/cheaper for routine edits', {
    emoji: '🎚️',
    funFact: '/model switches mid-session. Your quiz:regen uses opus for question-writing while the weekly review runs sonnet — same principle.',
  }),
  {
    id: 'cc-16',
    topicId: CC,
    type: 'write',
    prompt: 'Type the filename of the project memory file Claude Code auto-reads at session start:',
    emoji: '✍️',
    accept: ['CLAUDE.md', 'claude md', 'claude.md'],
    weight: 2,
    points: 8,
    status: 'active',
    createdAt: AT,
    funFact: 'There\'s also ~/.claude/CLAUDE.md for personal, cross-project preferences.',
  },
  {
    id: 'cc-17',
    topicId: CC,
    type: 'match',
    prompt: 'Match each command/flag to its purpose:',
    emoji: '🔗',
    pairs: [
      { left: '/compact', right: 'Summarize chat to free tokens' },
      { left: '/clear', right: 'Wipe the context fully' },
      { left: '/init', right: 'Generate CLAUDE.md' },
      { left: '-p', right: 'Headless one-shot run' },
    ],
    weight: 2,
    points: 10,
    status: 'active',
    createdAt: AT,
    funFact: 'Four commands that cover 80% of daily context & automation management.',
  },
  choice('cc-18', CC, 'Extended thinking is worth switching on when…', [
    'Renaming a variable',
    'The problem needs real reasoning — tricky architecture, gnarly debugging, subtle tradeoffs',
    'You want shorter answers',
    'The context is full',
  ], 'The problem needs real reasoning — tricky architecture, gnarly debugging, subtle tradeoffs', {
    emoji: '🤔',
    funFact: 'Thinking tokens cost money — spend them on problems where being wrong costs more.',
  }),
  choice('cc-19', CC, 'A powerful headless pattern for pipelines is…', [
    'Screenshots of the terminal',
    'Piping data in and JSON out: `cat report.csv | claude -p "…" --output-format json | jq …`',
    'Emailing prompts to the API',
    'Running claude inside vim',
  ], 'Piping data in and JSON out: `cat report.csv | claude -p "…" --output-format json | jq …`', {
    emoji: '🔁',
    funFact: 'Claude becomes a unix tool: composable, schedulable, diffable. That\'s the "AI in CI" skill hiring managers ask about.',
  }),
  choice('cc-20', CC, '--dangerously-skip-permissions is acceptable…', [
    'Whenever prompts get annoying',
    'In isolated/sandboxed environments (containers) for unattended runs — never on your main machine with secrets',
    'Only on Fridays',
    'When the repo is small',
  ], 'In isolated/sandboxed environments (containers) for unattended runs — never on your main machine with secrets', {
    emoji: '⚠️',
    funFact: 'The pros pair "YOLO mode" with a devcontainer that has no credentials and a firewalled network. Autonomy scales with isolation.',
  }),
]

export const AI_DEV_SEED: QuizQuestion[] = [...AI_SOFTWARE_DEV, ...COPILOT, ...CLAUDE_CODE]
