// Critical Thinking & Media Literacy — 50 seed questions, tuned for Ben (born Feb 2014, grade 6).
// Core material (weight 2): spotting scams and phishing, checking sources, protecting private info,
// telling ads from real content, recognising AI-generated and fake news.
// Fun extras (weight 1): clickbait, "free Robux" gaming scams, sponsored videos, internet gut-checks.
// This file only seeds Firestore (app/quizBank) on first run — after that, the bank
// in Firestore is the source of truth (removals, AI-regenerated questions, edits).
import type { QuizQuestion } from '../types'

const AT = '2026-07-19T00:00:00.000Z'
const T = 'critical-thinking-6'

const choice = (
  id: string,
  prompt: string,
  choices: string[],
  answer: string,
  opts: Partial<QuizQuestion> = {},
): QuizQuestion => ({
  id,
  topicId: T,
  type: 'choice',
  prompt,
  choices,
  answer,
  weight: 2,
  points: 8,
  status: 'active',
  createdAt: AT,
  ...opts,
})

export const CRITICAL_THINKING_6_SEED: QuizQuestion[] = [
  // --- gaming scams ---------------------------------------------------------
  choice(
    'ct-01',
    'A website says “Enter your Roblox username and password for 10,000 FREE Robux!” What is the ONE safe thing to do?',
    [
      'Close the site and never type your password there',
      'Type your password but change it back afterwards',
      'Enter a friend’s password instead of your own',
      'Enter your password but only half of it',
      'Enter your password on your phone instead of the computer',
      'Enter it, then quickly log out to cancel the theft',
      'Enter your password and screenshot the page as proof',
    ],
    'Close the site and never type your password there',
    {
      emoji: '🚫',
      funFact: 'Roblox never gives Robux away for your password. Only roblox.com can ever ask for your Roblox password.',
    },
  ),
  choice(
    'ct-02',
    'What is the real reason “free Robux generator” websites exist?',
    [
      'To steal accounts or make money from you',
      'To help players who cannot afford Robux',
      'To test new Roblox features before release',
      'To reward players who watch the most videos',
      'To let Roblox hand out leftover Robux',
      'To give Robux to players in countries without card payments',
      'To thank loyal players for years of playing',
    ],
    'To steal accounts or make money from you',
    {
      emoji: '💸',
      funFact: 'Robux only exist inside Roblox’s own computers. No outside website can create even one.',
    },
  ),
  choice(
    'ct-03',
    'In a game, someone says “Give me your rare item and I’ll send back two better ones.” What does this scam rely on?',
    [
      'You trusting a stranger to keep a promise',
      'A bug in the game’s trading code',
      'Your internet connection being slow',
      'The game servers being down for maintenance',
      'You having too many items in your inventory',
      'Your account being younger than 30 days',
      'You playing on a phone instead of a computer',
    ],
    'You trusting a stranger to keep a promise',
    {
      emoji: '🤝',
      funFact: 'Scammers call this a “trust trade”. Once the item leaves your account, nobody can force them to send anything back.',
    },
  ),
  choice(
    'ct-04',
    'A player messages “I’m a Roblox admin, send me your password to verify your account.” What is TRUE?',
    [
      'Real staff never ask for your password',
      'Real admins ask for passwords during safety checks',
      'Admins can only verify accounts through private messages',
      'You should send it if their name has “ADMIN” in it',
      'You should send it if they have a verified badge',
      'You should send it but only in a private server',
      'Admins need your password to give you your daily reward',
    ],
    'Real staff never ask for your password',
    {
      emoji: '🕵️',
      funFact: 'No real company — game, bank or school — ever needs your password. They can already see your account from their side.',
    },
  ),
  choice(
    'ct-05',
    'What does the word “phishing” mean online?',
    [
      'Tricking someone into giving up passwords or personal info',
      'Downloading games from unofficial websites',
      'Playing a game for many hours without a break',
      'Writing mean comments under someone’s video',
      'Copying someone else’s homework from the internet',
      'Watching videos with the sound turned off',
      'Buying items in a game with real money',
    ],
    'Tricking someone into giving up passwords or personal info',
    {
      emoji: '🎣',
      funFact: 'It is spelled with “ph” because early phone hackers called themselves “phreaks”. The bait is the fake message; you are the fish.',
    },
  ),
  choice(
    'ct-06',
    'Which of these is the STRONGEST sign an email is a phishing attempt?',
    [
      'It urgently demands your password or card number',
      'It contains a picture of the company logo',
      'It arrived later in the evening than usual',
      'It was sent to you and several other people',
      'It is longer than most emails you get',
      'It uses your first name in the greeting',
      'It has an unsubscribe link at the bottom',
    ],
    'It urgently demands your password or card number',
    {
      emoji: '📧',
      funFact: 'Scammers love urgency — “act in 24 hours!” — because scared people stop thinking carefully.',
    },
  ),
  choice(
    'ct-07',
    'A text says “Your parcel is stuck! Pay $2 at this link.” You ordered nothing. What is the best move?',
    [
      'Delete it and tell a parent — do not tap the link',
      'Tap the link to see which parcel it is',
      'Pay the $2 because it is only a small amount',
      'Reply “STOP” so they remove your number',
      'Reply asking which company sent the parcel',
      'Forward it to your friends to warn them',
      'Tap the link but close it quickly',
    ],
    'Delete it and tell a parent — do not tap the link',
    {
      emoji: '📦',
      funFact: 'The tiny $2 is not the point — the form steals your card number for much bigger charges later.',
    },
  ),

  // --- clickbait & headlines -----------------------------------------------
  choice(
    'ct-08',
    'What is “clickbait”?',
    [
      'A title made exciting on purpose to get clicks',
      'A video that is longer than one hour',
      'A comment posted by the video’s creator',
      'An advert that plays before a video starts',
      'A link that has been shortened to save space',
      'A thumbnail that shows the real ending',
      'A video that has been uploaded twice by mistake',
    ],
    'A title made exciting on purpose to get clicks',
    {
      emoji: '🪝',
      weight: 1,
      points: 5,
      funFact: 'Creators earn money per view, so a shocking title can literally pay better than a truthful one.',
    },
  ),
  choice(
    'ct-09',
    'Which headline is the clearest example of clickbait?',
    [
      'You WON’T BELIEVE what this dog did next!!!',
      'Local dog rescued from river by firefighters',
      'Dog show returns to Toronto this weekend',
      'Study finds dogs recognise their owners’ voices',
      'City council votes on new dog park rules',
      'Vet explains how to brush a dog’s teeth',
      'Missing dog found safe after three days',
    ],
    'You WON’T BELIEVE what this dog did next!!!',
    {
      emoji: '📰',
      weight: 1,
      points: 5,
      funFact: 'Clickbait hides the actual fact so you must click. Real headlines tell you the news up front.',
    },
  ),
  choice(
    'ct-10',
    'A video thumbnail shows something that never appears in the video. What is that called?',
    [
      'A misleading thumbnail',
      'A copyright strike',
      'A community post',
      'A playlist preview',
      'A closed caption',
      'An end screen',
      'A channel trailer',
    ],
    'A misleading thumbnail',
    {
      emoji: '🖼️',
      weight: 1,
      points: 5,
      funFact: 'Some creators test a dozen thumbnails and keep whichever gets the most clicks — truth is not part of the test.',
    },
  ),

  // --- ads & sponsorship ----------------------------------------------------
  choice(
    'ct-11',
    'A YouTuber says “Thanks to BLIP Snacks for sponsoring this video.” What does that mean?',
    [
      'A company paid them to talk about it',
      'They bought the snacks with their own money',
      'They are giving the snacks away for free',
      'YouTube chose the snack brand for them',
      'The snack company owns the channel',
      'Viewers voted for the snack in a poll',
      'The snacks were a gift from a fan',
    ],
    'A company paid them to talk about it',
    {
      emoji: '💰',
      funFact: 'In Canada and many countries, paid promotions must be labelled — that little “includes paid promotion” banner is the law working.',
    },
  ),
  choice(
    'ct-12',
    'Why should you be extra careful with a review from a SPONSORED video?',
    [
      'The reviewer was paid, so they may hide the bad parts',
      'Sponsored videos are always completely made up',
      'Sponsored videos cannot show the real product',
      'The reviewer has never used the product at all',
      'Sponsored videos are illegal in most countries',
      'The company writes every word the reviewer says',
      'Sponsored videos are removed after one week',
    ],
    'The reviewer was paid, so they may hide the bad parts',
    {
      emoji: '⚖️',
      funFact: 'A sponsored review is not automatically a lie — but it is an advert wearing a friendly hoodie. Check an unpaid review too.',
    },
  ),
  choice(
    'ct-13',
    'An ad promises “Get taller in 7 days — guaranteed!” What should that promise make you feel?',
    [
      'Suspicious, because it sounds too good to be true',
      'Excited, because it says “guaranteed”',
      'Relieved, because there is a money-back offer',
      'Confident, because it gives an exact number of days',
      'Convinced, because it appeared on a big website',
      'Reassured, because a doctor is pictured in it',
      'Certain, because thousands of people liked it',
    ],
    'Suspicious, because it sounds too good to be true',
    {
      emoji: '🤨',
      funFact: 'The oldest rule on the internet: if it sounds too good to be true, it is an advert, a scam, or both.',
    },
  ),
  choice(
    'ct-14',
    'In a mobile game, a tiny “X” is hard to find on an advert. Why do designers do that?',
    [
      'So you tap the ad by accident',
      'So the game loads faster',
      'So the game uses less battery',
      'To follow app store safety rules',
      'To keep the screen from getting too bright',
      'Because small buttons are easier for kids',
      'To leave more room for the game’s music player',
    ],
    'So you tap the ad by accident',
    {
      emoji: '❌',
      weight: 1,
      points: 5,
      funFact: 'Designers call sneaky tricks like this “dark patterns”. Accidental taps still count as clicks — and clicks pay.',
    },
  ),

  // --- fake news & sources --------------------------------------------------
  choice(
    'ct-15',
    'What is the BEST first step to check whether a shocking news story is true?',
    [
      'See if trusted news sites also report it',
      'Check how many likes the post has',
      'See whether the post uses capital letters',
      'Count how many people shared it',
      'Read the comments to see if people agree',
      'Check whether the photo looks dramatic',
      'See if a friend posted it too',
    ],
    'See if trusted news sites also report it',
    {
      emoji: '🔍',
      funFact: 'Journalists call this “corroboration”. One source is a rumour; several independent ones is a story.',
    },
  ),
  choice(
    'ct-16',
    'A post says “Scientists say chocolate cures colds.” Which question checks it best?',
    [
      'Which scientists, and where was the study published?',
      'Does chocolate taste good to most people?',
      'How many people shared the post today?',
      'Is the person who posted it popular?',
      'Does the post have a nice picture of chocolate?',
      'How long ago was the post written?',
      'Do your friends also like chocolate?',
    ],
    'Which scientists, and where was the study published?',
    {
      emoji: '🔬',
      funFact: '“Scientists say” with no names is a huge red flag. Real studies always have authors and a journal.',
    },
  ),
  choice(
    'ct-17',
    'You see a dramatic photo of a flood in your city. What is the smartest check?',
    [
      'Do a reverse image search to see where it came from',
      'Zoom in to see if the water looks real',
      'Count how many angry comments it has',
      'Check whether it is in colour or black and white',
      'See if the photo is blurry or sharp',
      'Check whether it has a filter applied',
      'See how many emojis are in the caption',
    ],
    'Do a reverse image search to see where it came from',
    {
      emoji: '🖥️',
      funFact: 'Most “breaking news” photos that go viral are real photos — from a different country, years earlier.',
    },
  ),
  choice(
    'ct-18',
    'Which of these is generally the MOST reliable source for a school project fact?',
    [
      'An encyclopedia or government website',
      'A random comment under a video',
      'A meme shared in a group chat',
      'A forum post by an anonymous user',
      'A friend who “heard it somewhere”',
      'A satire site that jokes about the news',
      'An advert for a product about the topic',
    ],
    'An encyclopedia or government website',
    {
      emoji: '📚',
      funFact: 'Even good encyclopedias list their own sources at the bottom — following those links is next-level research.',
    },
  ),
  choice(
    'ct-19',
    'What is a “satire” website?',
    [
      'A site that writes fake news as a joke',
      'A site that only reports sports results',
      'A site that hosts other people’s videos',
      'A site that sells products from many brands',
      'A site that lets you build your own web page',
      'A site that stores your photos online',
      'A site that translates news into other languages',
    ],
    'A site that writes fake news as a joke',
    {
      emoji: '🎭',
      weight: 1,
      points: 5,
      funFact: 'Satire is meant to be funny, but screenshots lose the joke — millions have shared satire believing it was real.',
    },
  ),
  choice(
    'ct-20',
    'A story has no author name, no date, and lots of spelling mistakes. What does that suggest?',
    [
      'It is probably not a careful, trustworthy source',
      'It was definitely written by a real journalist',
      'It must be breaking news written in a rush',
      'It is a government report',
      'It was translated by a professional',
      'It is a scientific paper',
      'It has been fact-checked by experts',
    ],
    'It is probably not a careful, trustworthy source',
    {
      emoji: '🧐',
      funFact: 'Real newsrooms have editors whose whole job is catching mistakes before publishing.',
    },
  ),
  choice(
    'ct-21',
    'What does “bias” mean when talking about news?',
    [
      'Leaning towards one side of a story',
      'Writing a story very quickly',
      'Publishing a story on paper instead of online',
      'Using photographs instead of drawings',
      'Reporting only about local events',
      'Charging money to read an article',
      'Writing in a language other than English',
    ],
    'Leaning towards one side of a story',
    {
      emoji: '↔️',
      funFact: 'Everyone has some bias. The trick is not finding a perfect source — it is reading more than one.',
    },
  ),
  choice(
    'ct-22',
    'Two websites report the same event very differently. What is the smartest conclusion?',
    [
      'You should read both and look for the shared facts',
      'The longer article must be the true one',
      'The one with more pictures is more accurate',
      'The one you found first is the correct one',
      'The one with more shares is telling the truth',
      'Both must be completely made up',
      'The one with a nicer website design is right',
    ],
    'You should read both and look for the shared facts',
    {
      emoji: '🔀',
      funFact: 'Facts that appear in every version are usually solid. The parts that differ are opinion or error.',
    },
  ),

  // --- AI-generated content -------------------------------------------------
  choice(
    'ct-23',
    'What is a “deepfake”?',
    [
      'A fake video or voice made by AI to look real',
      'A video recorded deep underwater',
      'A very long video posted in one piece',
      'A video that plays in slow motion',
      'A photo taken at night with a flash',
      'A video with subtitles added later',
      'A game recording made with a phone',
    ],
    'A fake video or voice made by AI to look real',
    {
      emoji: '🤖',
      funFact: 'Deepfake voices are so good that scammers have phoned families pretending to be a relative in trouble.',
    },
  ),
  choice(
    'ct-24',
    'Which detail most often gives away an AI-generated PHOTO of a person?',
    [
      'Hands with the wrong number of fingers',
      'The photo being brightly lit',
      'The person smiling at the camera',
      'A blurry background behind the person',
      'The photo being in portrait orientation',
      'The person wearing a plain t-shirt',
      'The photo having a high resolution',
    ],
    'Hands with the wrong number of fingers',
    {
      emoji: '✋',
      funFact: 'Hands, text on signs, and jewellery are AI’s classic weak spots — though the models keep getting better.',
    },
  ),
  choice(
    'ct-25',
    'A chatbot confidently tells you a fact that turns out to be invented. What is that called?',
    [
      'A hallucination',
      'A firewall',
      'A software update',
      'A screenshot',
      'A download error',
      'A password reset',
      'A browser cookie',
    ],
    'A hallucination',
    {
      emoji: '💭',
      funFact: 'AI models predict likely-sounding words, so a wrong answer sounds exactly as confident as a right one.',
    },
  ),
  choice(
    'ct-26',
    'You use an AI chatbot for homework. What is the responsible thing to do with its facts?',
    [
      'Check them against a reliable source before using them',
      'Copy them straight into your homework',
      'Trust them because AI reads the whole internet',
      'Assume they are right if the answer is long',
      'Assume they are right if it sounds confident',
      'Trust them if the AI is a paid version',
      'Trust them if the AI gives the same answer twice',
    ],
    'Check them against a reliable source before using them',
    {
      emoji: '✅',
      funFact: 'Asking an AI the same question twice can give two different answers — agreeing with itself proves nothing.',
    },
  ),
  choice(
    'ct-27',
    'A video shows a famous person saying something shocking. What is the best first check?',
    [
      'Look for the same clip on that person’s official channel',
      'Check if the video has loud background music',
      'See whether the video is in high definition',
      'Count how many times it has been shared',
      'Read the top comment to see what people think',
      'Check whether the person is wearing a suit',
      'See whether the video is longer than a minute',
    ],
    'Look for the same clip on that person’s official channel',
    {
      emoji: '🎬',
      funFact: 'If a world-famous person really said something huge, it will be on their own accounts and on real news sites within hours.',
    },
  ),

  // --- privacy --------------------------------------------------------------
  choice(
    'ct-28',
    'Which of these should you NEVER share with a stranger online?',
    [
      'Your home address',
      'Your favourite colour',
      'Your favourite video game',
      'The name of a book you enjoyed',
      'Your opinion about a movie',
      'Your favourite pizza topping',
      'The sport you like watching',
    ],
    'Your home address',
    {
      emoji: '🏠',
      funFact: 'Even a background detail like your school jacket in a photo can tell a stranger where to find you.',
    },
  ),
  choice(
    'ct-29',
    'What makes a password strong?',
    [
      'It is long and hard for others to guess',
      'It is your first name plus your birth year',
      'It is short so you never forget it',
      'It is the same one you use everywhere',
      'It is the word “password” with a capital P',
      'It is your pet’s name spelled backwards',
      'It is the numbers 1 to 8 in order',
    ],
    'It is long and hard for others to guess',
    {
      emoji: '🔐',
      funFact: 'A silly four-word phrase like “purple-otter-sings-loudly” beats “P@ss1” — length matters more than symbols.',
    },
  ),
  choice(
    'ct-30',
    'A game asks you to log in using a link a stranger sent in chat. What should you do?',
    [
      'Refuse and only log in through the official app or site',
      'Log in but use a different password than usual',
      'Log in quickly so the link does not expire',
      'Log in and then change your username',
      'Log in on a friend’s device instead',
      'Log in and then clear your browser history',
      'Log in but tick “do not remember me”',
    ],
    'Refuse and only log in through the official app or site',
    {
      emoji: '🔗',
      funFact: 'Fake login pages can look pixel-perfect. The address bar is the giveaway — always check it yourself.',
    },
  ),
  choice(
    'ct-31',
    'Why is it risky to post a photo of your new bus pass or ID card?',
    [
      'It can show personal details a stranger could misuse',
      'It uses too much of your phone’s storage',
      'It makes your photos load slowly',
      'It drains your phone battery faster',
      'It can make your camera lens dirty',
      'It stops you from posting other photos that day',
      'It uses up your monthly data allowance',
    ],
    'It can show personal details a stranger could misuse',
    {
      emoji: '🪪',
      funFact: 'People have had accounts stolen from a birthday visible in a photo — many services use it to verify you.',
    },
  ),
  choice(
    'ct-32',
    'Someone online you have never met asks to meet you in person. What is the right response?',
    [
      'Say no and tell a trusted adult',
      'Agree but meet in a quiet place',
      'Agree if they send a photo of themselves first',
      'Agree if they say they are your age',
      'Agree but do not tell anyone about it',
      'Agree if you have chatted for a long time',
      'Agree if they have lots of followers',
    ],
    'Say no and tell a trusted adult',
    {
      emoji: '🛡️',
      funFact: 'Anyone online can claim any age. Telling a trusted adult is not tattling — it is the actual correct move.',
    },
  ),
  choice(
    'ct-33',
    'What is two-factor authentication (2FA)?',
    [
      'A second check, like a code, on top of your password',
      'Using two different passwords for one account',
      'Having two accounts on the same game',
      'Logging in from two devices at once',
      'Changing your password twice a year',
      'Letting two friends share one account',
      'Two people approving a purchase together',
    ],
    'A second check, like a code, on top of your password',
    {
      emoji: '📱',
      funFact: '2FA stops most account thefts cold — even with your password, a thief still needs the phone in your pocket.',
    },
  ),

  // --- thinking skills ------------------------------------------------------
  choice(
    'ct-34',
    'What does it mean to check the SOURCE of a claim?',
    [
      'Finding out who originally said it and how they know',
      'Counting how many words the claim contains',
      'Checking the spelling of the claim',
      'Seeing which font the website uses',
      'Finding out what time it was posted',
      'Checking which country the reader is in',
      'Seeing whether it has a picture attached',
    ],
    'Finding out who originally said it and how they know',
    {
      emoji: '🧾',
      funFact: 'Fact-checkers call this “going upstream” — following a claim back to the original report.',
    },
  ),
  choice(
    'ct-35',
    'What is the difference between a FACT and an OPINION?',
    [
      'A fact can be checked; an opinion is what someone thinks',
      'A fact is longer; an opinion is shorter',
      'A fact is written by adults; an opinion by kids',
      'A fact appears in videos; an opinion in books',
      'A fact is boring; an opinion is interesting',
      'A fact is old news; an opinion is new news',
      'A fact needs a picture; an opinion does not',
    ],
    'A fact can be checked; an opinion is what someone thinks',
    {
      emoji: '🧠',
      funFact: '“Water boils at 100 °C” is a fact. “Boiled eggs are gross” is an opinion — no experiment settles it.',
    },
  ),
  choice(
    'ct-36',
    'A post claims 9 out of 10 kids prefer a snack, but only 10 kids were asked — all fans of that snack. What is wrong?',
    [
      'The group asked was too small and unfair',
      'The number 9 is too high to be believable',
      'Snacks cannot be measured scientifically',
      'The survey should have used percentages',
      'Kids are not allowed to answer surveys',
      'Ten is an unlucky number for surveys',
      'The survey was not posted on a news site',
    ],
    'The group asked was too small and unfair',
    {
      emoji: '📊',
      funFact: 'Who you ask decides the answer. Ask only fans and you will always get a fan-shaped result.',
    },
  ),
  choice(
    'ct-37',
    'What is an “echo chamber” online?',
    [
      'Only seeing posts that agree with what you already think',
      'A chat room with a loud microphone effect',
      'A video with the sound repeated twice',
      'A group chat with more than 50 people',
      'A website that copies articles from other sites',
      'A comment section that is turned off',
      'A livestream with a delay before it appears',
    ],
    'Only seeing posts that agree with what you already think',
    {
      emoji: '🔁',
      weight: 1,
      points: 5,
      funFact: 'Apps show you more of whatever you stop scrolling for — so your feed slowly becomes a mirror.',
    },
  ),
  choice(
    'ct-38',
    'Someone in a comment argues by insulting the writer instead of the argument. What is that?',
    [
      'A personal attack that dodges the actual point',
      'A well-supported counter-argument',
      'A request for more evidence',
      'A neutral summary of both sides',
      'A polite correction of a small error',
      'A citation of a reliable source',
      'A clarifying follow-up question',
    ],
    'A personal attack that dodges the actual point',
    {
      emoji: '🗯️',
      weight: 1,
      points: 5,
      funFact: 'Its old Latin name is “ad hominem” — literally “at the man”. Insults are not evidence.',
    },
  ),
  choice(
    'ct-39',
    'A message says “Forward this to 10 friends or you’ll have bad luck!” What is it?',
    [
      'A chain message with no real power',
      'A safety warning from the app',
      'A genuine test of your friendships',
      'An official message from the phone company',
      'A message that unlocks a hidden feature',
      'A survey that collects opinions',
      'A birthday reminder system',
    ],
    'A chain message with no real power',
    {
      emoji: '⛓️',
      weight: 1,
      points: 5,
      funFact: 'Chain letters existed on paper long before phones. Nothing bad happens when you delete one.',
    },
  ),
  choice(
    'ct-40',
    'A pop-up shouts “WARNING! Your device has 5 viruses! Click to clean now!” What is really happening?',
    [
      'It is a fake alert trying to make you install something bad',
      'Your device has scanned itself and found real viruses',
      'Your internet provider is warning you',
      'The website is running a helpful free antivirus',
      'Your browser has blocked five harmful sites',
      'A system update is ready to install',
      'Your storage is nearly full',
    ],
    'It is a fake alert trying to make you install something bad',
    {
      emoji: '⚠️',
      funFact: 'A web page cannot scan your device. Any site claiming to have found viruses is lying by definition.',
    },
  ),
  choice(
    'ct-41',
    'A giveaway account with 3 followers and no history promises a free console. What is the biggest clue it is fake?',
    [
      'A brand-new account with almost no followers',
      'The console is an expensive model',
      'The post was made in the evening',
      'The post uses more than one photo',
      'The post has a long caption',
      'The account name contains numbers',
      'The post has comments turned on',
    ],
    'A brand-new account with almost no followers',
    {
      emoji: '🎁',
      funFact: 'Real giveaways come from accounts with a long history you can scroll back through. Scam accounts are days old.',
    },
  ),

  // --- write-in -------------------------------------------------------------
  {
    id: 'ct-42',
    topicId: T,
    type: 'write',
    prompt: 'What word describes fake messages that trick you into giving away passwords? (starts with “ph”)',
    emoji: '🎣',
    accept: ['Phishing'],
    weight: 2,
    points: 8,
    status: 'active',
    createdAt: AT,
    funFact: 'Phishing is the number one way accounts get stolen — far more common than clever hacking.',
  },
  {
    id: 'ct-43',
    topicId: T,
    type: 'write',
    prompt: 'Type the word for a video or voice faked by AI to look like a real person:',
    emoji: '🤖',
    accept: ['Deepfake', 'Deep fake'],
    weight: 2,
    points: 8,
    status: 'active',
    createdAt: AT,
    funFact: 'The name mixes “deep learning” (the AI method) with “fake”.',
  },
  {
    id: 'ct-44',
    topicId: T,
    type: 'write',
    prompt: 'Type the word for an exaggerated title designed just to make you click:',
    emoji: '🪝',
    accept: ['Clickbait', 'Click bait'],
    weight: 1,
    points: 5,
    status: 'active',
    createdAt: AT,
    funFact: 'Some platforms now push down videos people click and then instantly leave — clickbait can backfire.',
  },
  {
    id: 'ct-45',
    topicId: T,
    type: 'write',
    prompt: 'A statement that can be proved true or false is called a ____. (one word)',
    emoji: '🧠',
    accept: ['Fact'],
    weight: 2,
    points: 8,
    status: 'active',
    createdAt: AT,
    funFact: 'The opposite is an opinion — no amount of arguing turns one into the other.',
  },
  {
    id: 'ct-46',
    topicId: T,
    type: 'write',
    prompt: 'Type the secret word or phrase you should never share with anyone online:',
    emoji: '🔐',
    accept: ['Password', 'My password'],
    weight: 2,
    points: 8,
    status: 'active',
    createdAt: AT,
    funFact: 'Not even your best friend needs it. Sharing a password is how “friend drama” becomes “account stolen”.',
  },

  // --- match ----------------------------------------------------------------
  {
    id: 'ct-47',
    topicId: T,
    type: 'match',
    prompt: 'Match each online trick to what it is really after:',
    emoji: '🔗',
    pairs: [
      { left: 'Free Robux generator', right: 'Your account password' },
      { left: 'Fake parcel text', right: 'Your card number' },
      { left: 'Clickbait title', right: 'Your click and views' },
      { left: 'Fake virus pop-up', right: 'You installing bad software' },
    ],
    weight: 2,
    points: 10,
    status: 'active',
    createdAt: AT,
    funFact: 'Every scam wants one of three things: your password, your money, or your device.',
  },
  {
    id: 'ct-48',
    topicId: T,
    type: 'match',
    prompt: 'Match each term to its meaning:',
    emoji: '📖',
    pairs: [
      { left: 'Phishing', right: 'Tricking you into giving up secrets' },
      { left: 'Deepfake', right: 'AI-made video of a real person' },
      { left: 'Bias', right: 'Leaning towards one side' },
      { left: 'Satire', right: 'Fake news written as a joke' },
    ],
    weight: 2,
    points: 10,
    status: 'active',
    createdAt: AT,
    funFact: 'Knowing the name of a trick makes it much easier to spot in the wild.',
  },

  // --- order ----------------------------------------------------------------
  {
    id: 'ct-49',
    topicId: T,
    type: 'order',
    prompt: 'You get a “you won a prize!” message. Put these steps in the RIGHT order, first to last:',
    emoji: '🧭',
    sequence: [
      'Stop and do not tap the link',
      'Ask who really sent it',
      'Check the company’s official site or app',
      'Tell a trusted adult and delete the message',
    ],
    weight: 2,
    points: 10,
    status: 'active',
    createdAt: AT,
    funFact: 'Stopping first is the whole trick. Scams work on speed, so slowing down beats them.',
  },
  {
    id: 'ct-50',
    topicId: T,
    type: 'order',
    prompt: 'Order these sources from MOST trustworthy to LEAST for a school fact:',
    emoji: '📚',
    sequence: [
      'A government or university website',
      'A well-known news organisation',
      'A random blog post',
      'An anonymous comment under a video',
    ],
    weight: 1,
    points: 6,
    status: 'active',
    createdAt: AT,
    funFact: 'Trustworthy sources share one habit: they show where their information came from.',
  },
]
