// AUTO-GENERATED by scripts/backgrounds.mjs — do not edit.
// Drop images into public/backgrounds/ and run `npm run backgrounds` (also runs before dev/build).
export const BACKGROUND_CATALOG = [
  "01fda5ba4ee8b5f3cdb9f37cf0081a2d.jpg",
  "bg1.jpg",
  "bg2.jpeg",
  "bg3.jpeg",
  "bg4.jpeg",
  "bg5.webp",
  "bg6.jpg",
  "bg7.jpg",
  "bg8.webp",
  "bg9.jpg",
  "bg10.jpg",
  "bg11.jpg",
  "bg12.jpg",
  "bg13.jpg",
  "bg14.jpeg",
  "bg15.jpg",
  "thumb-1920-1001303.jpg"
]
