// AUTO-GENERATED by scripts/stickers.mjs — do not edit.
// Drop images into assets/Album/ (or assets/Album/special stickers/ for red rares)
// and run `npm run stickers` (also runs before dev/build).
/** The six battle elements, in ring order: each one beats the NEXT in this list. */
export type CardElement = 'flame' | 'beast' | 'blade' | 'spirit' | 'storm' | 'tide'

export type CardArchetype = 'guardian' | 'bruiser' | 'striker' | 'trickster'

/** What a finisher does on top of its damage. Strikers trade this for raw power. */
export type CardEffect = 'heal' | 'boost' | 'stun' | 'drain'

export interface CardAttack {
  name: string
  cost: number // energy spent to use it
  damage: number
  effect?: CardEffect
  amount?: number // heal/boost magnitude
  text?: string // the effect line printed on the card
}

/** A sticker's Davy Back Duel identity — derived from its id, so it never drifts. */
export interface CardStats {
  element: CardElement
  archetype: CardArchetype
  hp: number
  retreat: number // energy to swap this card off the front line
  /** [quick move, finisher] */
  attacks: CardAttack[]
  /**
   * Clip in public/duel/voices/ this character shouts on a finisher. Only set for
   * characters we recognise by name; everyone else uses their element's sound.
   */
  voice?: string
}

export interface StickerDef {
  id: string
  name: string
  rarity: 'common' | 'special'
  crew: string
  card: CardStats
}

export interface CrewDef {
  id: string
  name: string
  /** path under public/ to the team's flag, e.g. /flags/br.webp */
  flag: string
}

/** Cards each team holds — the album is "complete-able" in blocks of this. */
export const CARDS_PER_TEAM = 8

/** Every country that played the World Cup 2026 — teams still waiting for images. */
export const TOTAL_WC_TEAMS = 42

export const STICKER_CREWS: CrewDef[] = [
  {
    "id": "argentina",
    "name": "Argentina",
    "flag": "/flags/ar.webp"
  },
  {
    "id": "spain",
    "name": "Spain",
    "flag": "/flags/es.webp"
  },
  {
    "id": "france",
    "name": "France",
    "flag": "/flags/fr.webp"
  },
  {
    "id": "england",
    "name": "England",
    "flag": "/flags/gb-eng.webp"
  },
  {
    "id": "brazil",
    "name": "Brazil",
    "flag": "/flags/br.webp"
  },
  {
    "id": "portugal",
    "name": "Portugal",
    "flag": "/flags/pt.webp"
  },
  {
    "id": "netherlands",
    "name": "Netherlands",
    "flag": "/flags/nl.webp"
  },
  {
    "id": "belgium",
    "name": "Belgium",
    "flag": "/flags/be.webp"
  },
  {
    "id": "germany",
    "name": "Germany",
    "flag": "/flags/de.webp"
  }
]

/**
 * The weakness ring — `beats` takes DOUBLE damage from this element. Rendered
 * as-is on the duel's How to Play page, so the rules can never fall out of sync
 * with the maths.
 */
export const CARD_ELEMENTS: { id: CardElement; name: string; icon: string; beats: CardElement }[] = [
  {
    "id": "flame",
    "name": "Flame",
    "icon": "🔥",
    "beats": "beast"
  },
  {
    "id": "beast",
    "name": "Beast",
    "icon": "🐗",
    "beats": "blade"
  },
  {
    "id": "blade",
    "name": "Blade",
    "icon": "⚔️",
    "beats": "spirit"
  },
  {
    "id": "spirit",
    "name": "Spirit",
    "icon": "👻",
    "beats": "storm"
  },
  {
    "id": "storm",
    "name": "Storm",
    "icon": "⚡",
    "beats": "tide"
  },
  {
    "id": "tide",
    "name": "Tide",
    "icon": "🌊",
    "beats": "flame"
  }
]

export const CARD_ARCHETYPES: { id: CardArchetype; label: string; blurb: string }[] = [
  {
    "id": "guardian",
    "label": "Guardian",
    "blurb": "Huge HP, small hits — its finisher heals."
  },
  {
    "id": "bruiser",
    "label": "Bruiser",
    "blurb": "Tough and steady — its finisher powers up the next hit."
  },
  {
    "id": "striker",
    "label": "Striker",
    "blurb": "Glass cannon: hits hardest, folds fastest."
  },
  {
    "id": "trickster",
    "label": "Trickster",
    "blurb": "Fragile, but its finisher stuns for a turn."
  }
]

export const STICKER_CATALOG: StickerDef[] = [
  {
    "id": "6c224f4a20a4462309f75700c378650e0cf3d7ca7904-3-4",
    "name": "Smoker",
    "rarity": "common",
    "crew": "brazil",
    "card": {
      "element": "spirit",
      "archetype": "guardian",
      "hp": 150,
      "retreat": 2,
      "attacks": [
        {
          "name": "White Blow",
          "cost": 1,
          "damage": 20
        },
        {
          "name": "White Out",
          "cost": 2,
          "damage": 50,
          "effect": "heal",
          "amount": 20,
          "text": "Heal 20 HP"
        }
      ]
    }
  },
  {
    "id": "7a094561ead54385afc5120f89988e5d",
    "name": "Trafalgar D. Water Law",
    "rarity": "common",
    "crew": "france",
    "card": {
      "element": "spirit",
      "archetype": "trickster",
      "hp": 100,
      "retreat": 1,
      "attacks": [
        {
          "name": "Room: Shambles",
          "cost": 1,
          "damage": 20
        },
        {
          "name": "Gamma Knife",
          "cost": 2,
          "damage": 61,
          "effect": "stun",
          "text": "They can’t attack next turn"
        }
      ],
      "voice": "law"
    }
  },
  {
    "id": "9c04c508408a164911c0a0c44bf17851",
    "name": "Dracule Mihawk",
    "rarity": "common",
    "crew": "france",
    "card": {
      "element": "blade",
      "archetype": "striker",
      "hp": 80,
      "retreat": 1,
      "attacks": [
        {
          "name": "Hawk Slash",
          "cost": 1,
          "damage": 25
        },
        {
          "name": "Black Blade",
          "cost": 2,
          "damage": 90
        }
      ]
    }
  },
  {
    "id": "0045-2d-png",
    "name": "Mystery Pirate",
    "rarity": "special",
    "crew": "portugal",
    "card": {
      "element": "spirit",
      "archetype": "trickster",
      "hp": 130,
      "retreat": 1,
      "attacks": [
        {
          "name": "Unknown Strike",
          "cost": 1,
          "damage": 25
        },
        {
          "name": "Hidden Power",
          "cost": 3,
          "damage": 66,
          "effect": "stun",
          "text": "They can’t attack next turn"
        }
      ]
    }
  },
  {
    "id": "196-1967259-zoro-and-nami-chopper-transparent-on",
    "name": "Zoro, Nami & Chopper",
    "rarity": "special",
    "crew": "brazil",
    "card": {
      "element": "beast",
      "archetype": "guardian",
      "hp": 160,
      "retreat": 2,
      "attacks": [
        {
          "name": "Kung Fu Point",
          "cost": 1,
          "damage": 20
        },
        {
          "name": "Monster Point",
          "cost": 3,
          "damage": 60,
          "effect": "heal",
          "amount": 20,
          "text": "Heal 20 HP"
        }
      ],
      "voice": "chopper"
    }
  },
  {
    "id": "502-5029965-dead-bones-brook-sabo-one-piece-png",
    "name": "Brook & Sabo",
    "rarity": "common",
    "crew": "france",
    "card": {
      "element": "spirit",
      "archetype": "trickster",
      "hp": 120,
      "retreat": 1,
      "attacks": [
        {
          "name": "Hanauta Sancho",
          "cost": 1,
          "damage": 30
        },
        {
          "name": "Soul Solid",
          "cost": 2,
          "damage": 61,
          "effect": "stun",
          "text": "They can’t attack next turn"
        }
      ],
      "voice": "brook"
    }
  },
  {
    "id": "853b05215a6172af49ec86605791bb08",
    "name": "Sanji · Raid Suit",
    "rarity": "common",
    "crew": "argentina",
    "card": {
      "element": "flame",
      "archetype": "striker",
      "hp": 110,
      "retreat": 1,
      "attacks": [
        {
          "name": "Diable Jambe",
          "cost": 1,
          "damage": 25
        },
        {
          "name": "Hell Memories",
          "cost": 2,
          "damage": 85
        }
      ],
      "voice": "sanji"
    }
  },
  {
    "id": "8523302-eb2874b406880a99ca39ec0cc06b4dc4",
    "name": "Kozuki Oden",
    "rarity": "common",
    "crew": "portugal",
    "card": {
      "element": "blade",
      "archetype": "striker",
      "hp": 80,
      "retreat": 1,
      "attacks": [
        {
          "name": "Togen Totsuka",
          "cost": 1,
          "damage": 35
        },
        {
          "name": "Paradise Totsuka",
          "cost": 2,
          "damage": 80
        }
      ]
    }
  },
  {
    "id": "ace-and-luffy-png-clipart",
    "name": "Ace & Luffy",
    "rarity": "special",
    "crew": "argentina",
    "card": {
      "element": "beast",
      "archetype": "bruiser",
      "hp": 125,
      "retreat": 2,
      "attacks": [
        {
          "name": "Gum-Gum Pistol",
          "cost": 1,
          "damage": 30
        },
        {
          "name": "Gum-Gum Red Roc",
          "cost": 3,
          "damage": 72,
          "effect": "boost",
          "amount": 20,
          "text": "Next attack +20"
        }
      ],
      "voice": "luffy"
    }
  },
  {
    "id": "akainu-borsalino-one-piece-admiral-character-png",
    "name": "Akainu & Borsalino",
    "rarity": "common",
    "crew": "argentina",
    "card": {
      "element": "storm",
      "archetype": "striker",
      "hp": 110,
      "retreat": 1,
      "attacks": [
        {
          "name": "Yasakani no Magatama",
          "cost": 1,
          "damage": 30
        },
        {
          "name": "Amaterasu",
          "cost": 2,
          "damage": 80
        }
      ]
    }
  },
  {
    "id": "bartholomew-kuma-render",
    "name": "Bartholomew Kuma",
    "rarity": "common",
    "crew": "belgium",
    "card": {
      "element": "spirit",
      "archetype": "bruiser",
      "hp": 105,
      "retreat": 2,
      "attacks": [
        {
          "name": "Pad Cannon",
          "cost": 1,
          "damage": 20
        },
        {
          "name": "Ursus Shock",
          "cost": 2,
          "damage": 72,
          "effect": "boost",
          "amount": 20,
          "text": "Next attack +20"
        }
      ]
    }
  },
  {
    "id": "blackbeard-posttimeskip-original-fix",
    "name": "Marshall D. Teach",
    "rarity": "common",
    "crew": "brazil",
    "card": {
      "element": "spirit",
      "archetype": "bruiser",
      "hp": 115,
      "retreat": 2,
      "attacks": [
        {
          "name": "Black Hole",
          "cost": 1,
          "damage": 25
        },
        {
          "name": "Liberation",
          "cost": 2,
          "damage": 72,
          "effect": "boost",
          "amount": 20,
          "text": "Next attack +20"
        }
      ],
      "voice": "teach"
    }
  },
  {
    "id": "brook",
    "name": "Brook",
    "rarity": "common",
    "crew": "brazil",
    "card": {
      "element": "spirit",
      "archetype": "trickster",
      "hp": 90,
      "retreat": 1,
      "attacks": [
        {
          "name": "Hanauta Sancho",
          "cost": 1,
          "damage": 20
        },
        {
          "name": "Soul Solid",
          "cost": 2,
          "damage": 66,
          "effect": "stun",
          "text": "They can’t attack next turn"
        }
      ],
      "voice": "brook"
    }
  },
  {
    "id": "cavendish-one-piece",
    "name": "Cavendish",
    "rarity": "common",
    "crew": "england",
    "card": {
      "element": "blade",
      "archetype": "striker",
      "hp": 90,
      "retreat": 1,
      "attacks": [
        {
          "name": "Swan Lake",
          "cost": 1,
          "damage": 35
        },
        {
          "name": "Bloody Mary",
          "cost": 2,
          "damage": 85
        }
      ]
    }
  },
  {
    "id": "charlotte-katakuri-2",
    "name": "Charlotte Katakuri",
    "rarity": "common",
    "crew": "france",
    "card": {
      "element": "tide",
      "archetype": "bruiser",
      "hp": 135,
      "retreat": 2,
      "attacks": [
        {
          "name": "Mochi Spear",
          "cost": 1,
          "damage": 20
        },
        {
          "name": "Buzz Cut Mochi",
          "cost": 2,
          "damage": 72,
          "effect": "boost",
          "amount": 20,
          "text": "Next attack +20"
        }
      ],
      "voice": "katakuri"
    }
  },
  {
    "id": "cmelxgmy7wi4gxlhg9nswkxiwzi71nxwgm57a1x2n1whxuhz",
    "name": "Jinbe · Warlord",
    "rarity": "common",
    "crew": "brazil",
    "card": {
      "element": "tide",
      "archetype": "guardian",
      "hp": 140,
      "retreat": 2,
      "attacks": [
        {
          "name": "Fish-Man Karate",
          "cost": 1,
          "damage": 15
        },
        {
          "name": "Vagabond Drill",
          "cost": 2,
          "damage": 50,
          "effect": "heal",
          "amount": 20,
          "text": "Heal 20 HP"
        }
      ],
      "voice": "jinbe"
    }
  },
  {
    "id": "d4fty22-efc79fb4-86ee-4950-81f8-da8e362ba5ee",
    "name": "Tony Tony Chopper",
    "rarity": "common",
    "crew": "spain",
    "card": {
      "element": "beast",
      "archetype": "guardian",
      "hp": 130,
      "retreat": 2,
      "attacks": [
        {
          "name": "Kung Fu Point",
          "cost": 1,
          "damage": 20
        },
        {
          "name": "Monster Point",
          "cost": 2,
          "damage": 55,
          "effect": "heal",
          "amount": 20,
          "text": "Heal 20 HP"
        }
      ],
      "voice": "chopper"
    }
  },
  {
    "id": "dellinger-dorsal-fin",
    "name": "Dellinger",
    "rarity": "common",
    "crew": "portugal",
    "card": {
      "element": "beast",
      "archetype": "striker",
      "hp": 110,
      "retreat": 1,
      "attacks": [
        {
          "name": "Fighting Fish Kick",
          "cost": 1,
          "damage": 25
        },
        {
          "name": "Blood Frenzy",
          "cost": 2,
          "damage": 90
        }
      ]
    }
  },
  {
    "id": "denjiro-one-piece",
    "name": "Denjiro",
    "rarity": "common",
    "crew": "belgium",
    "card": {
      "element": "blade",
      "archetype": "guardian",
      "hp": 150,
      "retreat": 2,
      "attacks": [
        {
          "name": "Iai Draw",
          "cost": 1,
          "damage": 20
        },
        {
          "name": "Boss Slash",
          "cost": 2,
          "damage": 50,
          "effect": "heal",
          "amount": 20,
          "text": "Heal 20 HP"
        }
      ]
    }
  },
  {
    "id": "donquixote-rosinante",
    "name": "Donquixote Rosinante",
    "rarity": "common",
    "crew": "netherlands",
    "card": {
      "element": "spirit",
      "archetype": "guardian",
      "hp": 140,
      "retreat": 2,
      "attacks": [
        {
          "name": "Silent Room",
          "cost": 1,
          "damage": 25
        },
        {
          "name": "Calm Field",
          "cost": 2,
          "damage": 60,
          "effect": "heal",
          "amount": 20,
          "text": "Heal 20 HP"
        }
      ]
    }
  },
  {
    "id": "edwardnew",
    "name": "Edward Newgate",
    "rarity": "common",
    "crew": "germany",
    "card": {
      "element": "storm",
      "archetype": "bruiser",
      "hp": 135,
      "retreat": 2,
      "attacks": [
        {
          "name": "Quake Punch",
          "cost": 1,
          "damage": 30
        },
        {
          "name": "Sea Splitter",
          "cost": 2,
          "damage": 72,
          "effect": "boost",
          "amount": 20,
          "text": "Next attack +20"
        }
      ],
      "voice": "whitebeard"
    }
  },
  {
    "id": "enelrender",
    "name": "Enelrender",
    "rarity": "common",
    "crew": "spain",
    "card": {
      "element": "storm",
      "archetype": "striker",
      "hp": 100,
      "retreat": 1,
      "attacks": [
        {
          "name": "El Thor",
          "cost": 1,
          "damage": 35
        },
        {
          "name": "Deathpiea",
          "cost": 2,
          "damage": 85
        }
      ],
      "voice": "enel"
    }
  },
  {
    "id": "eustass-kid",
    "name": "Eustass Kid",
    "rarity": "common",
    "crew": "belgium",
    "card": {
      "element": "storm",
      "archetype": "bruiser",
      "hp": 135,
      "retreat": 2,
      "attacks": [
        {
          "name": "Repel",
          "cost": 1,
          "damage": 30
        },
        {
          "name": "Punk Gibson",
          "cost": 2,
          "damage": 62,
          "effect": "boost",
          "amount": 20,
          "text": "Next attack +20"
        }
      ]
    }
  },
  {
    "id": "franky-2-years-later",
    "name": "Franky",
    "rarity": "common",
    "crew": "brazil",
    "card": {
      "element": "storm",
      "archetype": "guardian",
      "hp": 150,
      "retreat": 2,
      "attacks": [
        {
          "name": "Strong Right",
          "cost": 1,
          "damage": 25
        },
        {
          "name": "Coup de Vent",
          "cost": 2,
          "damage": 60,
          "effect": "heal",
          "amount": 20,
          "text": "Heal 20 HP"
        }
      ],
      "voice": "franky"
    }
  },
  {
    "id": "g37ajdyxoaa6llq",
    "name": "Mystery Pirate",
    "rarity": "special",
    "crew": "spain",
    "card": {
      "element": "spirit",
      "archetype": "trickster",
      "hp": 120,
      "retreat": 1,
      "attacks": [
        {
          "name": "Unknown Strike",
          "cost": 1,
          "damage": 30
        },
        {
          "name": "Hidden Power",
          "cost": 3,
          "damage": 71,
          "effect": "stun",
          "text": "They can’t attack next turn"
        }
      ]
    }
  },
  {
    "id": "god-usopp-one-piece-elbaf-by-caiquenadal-df1j9ci",
    "name": "God Usopp Elbaf Caiquenadal ",
    "rarity": "common",
    "crew": "argentina",
    "card": {
      "element": "spirit",
      "archetype": "trickster",
      "hp": 100,
      "retreat": 1,
      "attacks": [
        {
          "name": "Impact Wolf",
          "cost": 1,
          "damage": 30
        },
        {
          "name": "Kabuto Firebird Star",
          "cost": 2,
          "damage": 56,
          "effect": "stun",
          "text": "They can’t attack next turn"
        }
      ],
      "voice": "usopp"
    }
  },
  {
    "id": "hajrudin-render",
    "name": "Hajrudin",
    "rarity": "common",
    "crew": "germany",
    "card": {
      "element": "beast",
      "archetype": "bruiser",
      "hp": 135,
      "retreat": 2,
      "attacks": [
        {
          "name": "Giant Stomp",
          "cost": 1,
          "damage": 20
        },
        {
          "name": "Bone Breaker",
          "cost": 2,
          "damage": 72,
          "effect": "boost",
          "amount": 20,
          "text": "Next attack +20"
        }
      ]
    }
  },
  {
    "id": "hybrid-queen",
    "name": "Queen · Hybrid",
    "rarity": "common",
    "crew": "germany",
    "card": {
      "element": "beast",
      "archetype": "trickster",
      "hp": 90,
      "retreat": 1,
      "attacks": [
        {
          "name": "Brachio Bomber",
          "cost": 1,
          "damage": 25
        },
        {
          "name": "Plague Rounds",
          "cost": 2,
          "damage": 66,
          "effect": "stun",
          "text": "They can’t attack next turn"
        }
      ]
    }
  },
  {
    "id": "image-1",
    "name": "Mystery Pirate",
    "rarity": "special",
    "crew": "england",
    "card": {
      "element": "spirit",
      "archetype": "trickster",
      "hp": 110,
      "retreat": 1,
      "attacks": [
        {
          "name": "Unknown Strike",
          "cost": 1,
          "damage": 30
        },
        {
          "name": "Hidden Power",
          "cost": 3,
          "damage": 71,
          "effect": "stun",
          "text": "They can’t attack next turn"
        }
      ]
    }
  },
  {
    "id": "image-2",
    "name": "Mystery Pirate",
    "rarity": "special",
    "crew": "brazil",
    "card": {
      "element": "spirit",
      "archetype": "trickster",
      "hp": 140,
      "retreat": 1,
      "attacks": [
        {
          "name": "Unknown Strike",
          "cost": 1,
          "damage": 35
        },
        {
          "name": "Hidden Power",
          "cost": 3,
          "damage": 76,
          "effect": "stun",
          "text": "They can’t attack next turn"
        }
      ]
    }
  },
  {
    "id": "image",
    "name": "Mystery Pirate",
    "rarity": "special",
    "crew": "netherlands",
    "card": {
      "element": "spirit",
      "archetype": "trickster",
      "hp": 140,
      "retreat": 1,
      "attacks": [
        {
          "name": "Unknown Strike",
          "cost": 1,
          "damage": 25
        },
        {
          "name": "Hidden Power",
          "cost": 3,
          "damage": 76,
          "effect": "stun",
          "text": "They can’t attack next turn"
        }
      ]
    }
  },
  {
    "id": "images-1",
    "name": "Usopp",
    "rarity": "common",
    "crew": "germany",
    "card": {
      "element": "spirit",
      "archetype": "trickster",
      "hp": 120,
      "retreat": 1,
      "attacks": [
        {
          "name": "Impact Wolf",
          "cost": 1,
          "damage": 25
        },
        {
          "name": "Kabuto Firebird Star",
          "cost": 2,
          "damage": 61,
          "effect": "stun",
          "text": "They can’t attack next turn"
        }
      ],
      "voice": "usopp"
    }
  },
  {
    "id": "images-1-xzc2",
    "name": "Mystery Pirate",
    "rarity": "special",
    "crew": "england",
    "card": {
      "element": "spirit",
      "archetype": "trickster",
      "hp": 140,
      "retreat": 1,
      "attacks": [
        {
          "name": "Unknown Strike",
          "cost": 1,
          "damage": 30
        },
        {
          "name": "Hidden Power",
          "cost": 3,
          "damage": 66,
          "effect": "stun",
          "text": "They can’t attack next turn"
        }
      ]
    }
  },
  {
    "id": "images",
    "name": "Portgas D. Ace",
    "rarity": "common",
    "crew": "belgium",
    "card": {
      "element": "flame",
      "archetype": "striker",
      "hp": 100,
      "retreat": 1,
      "attacks": [
        {
          "name": "Fire Fist",
          "cost": 1,
          "damage": 25
        },
        {
          "name": "Great Flame Commandment",
          "cost": 2,
          "damage": 90
        }
      ],
      "voice": "ace"
    }
  },
  {
    "id": "images-ir3h",
    "name": "Luffy · World Cup",
    "rarity": "special",
    "crew": "belgium",
    "card": {
      "element": "beast",
      "archetype": "bruiser",
      "hp": 155,
      "retreat": 2,
      "attacks": [
        {
          "name": "Gum-Gum Pistol",
          "cost": 1,
          "damage": 35
        },
        {
          "name": "Gum-Gum Red Roc",
          "cost": 3,
          "damage": 72,
          "effect": "boost",
          "amount": 20,
          "text": "Next attack +20"
        }
      ],
      "voice": "luffy"
    }
  },
  {
    "id": "imgbin-donquixote-doflamingo-one-piece-unlimited",
    "name": "Donquixote Doflamingo",
    "rarity": "common",
    "crew": "argentina",
    "card": {
      "element": "spirit",
      "archetype": "trickster",
      "hp": 100,
      "retreat": 1,
      "attacks": [
        {
          "name": "Parasite",
          "cost": 1,
          "damage": 30
        },
        {
          "name": "Overheat",
          "cost": 2,
          "damage": 56,
          "effect": "stun",
          "text": "They can’t attack next turn"
        }
      ],
      "voice": "doflamingo"
    }
  },
  {
    "id": "jinbe",
    "name": "Jinbe",
    "rarity": "common",
    "crew": "brazil",
    "card": {
      "element": "tide",
      "archetype": "guardian",
      "hp": 120,
      "retreat": 2,
      "attacks": [
        {
          "name": "Fish-Man Karate",
          "cost": 1,
          "damage": 20
        },
        {
          "name": "Vagabond Drill",
          "cost": 2,
          "damage": 50,
          "effect": "heal",
          "amount": 20,
          "text": "Heal 20 HP"
        }
      ],
      "voice": "jinbe"
    }
  },
  {
    "id": "kaidoh",
    "name": "Kaido",
    "rarity": "common",
    "crew": "germany",
    "card": {
      "element": "beast",
      "archetype": "guardian",
      "hp": 130,
      "retreat": 2,
      "attacks": [
        {
          "name": "Thunder Bagua",
          "cost": 1,
          "damage": 20
        },
        {
          "name": "Boro Breath",
          "cost": 2,
          "damage": 50,
          "effect": "heal",
          "amount": 20,
          "text": "Heal 20 HP"
        }
      ],
      "voice": "kaido"
    }
  },
  {
    "id": "kaidou-dragonform-original-enhanced",
    "name": "Kaido · Dragon Form",
    "rarity": "common",
    "crew": "argentina",
    "card": {
      "element": "beast",
      "archetype": "guardian",
      "hp": 130,
      "retreat": 2,
      "attacks": [
        {
          "name": "Thunder Bagua",
          "cost": 1,
          "damage": 15
        },
        {
          "name": "Boro Breath",
          "cost": 2,
          "damage": 50,
          "effect": "heal",
          "amount": 20,
          "text": "Heal 20 HP"
        }
      ],
      "voice": "kaido"
    }
  },
  {
    "id": "katakuri-2nd-son-of-the-charlotte-family-png-cli",
    "name": "Katakuri",
    "rarity": "special",
    "crew": "netherlands",
    "card": {
      "element": "tide",
      "archetype": "bruiser",
      "hp": 145,
      "retreat": 2,
      "attacks": [
        {
          "name": "Mochi Spear",
          "cost": 1,
          "damage": 25
        },
        {
          "name": "Buzz Cut Mochi",
          "cost": 3,
          "damage": 77,
          "effect": "boost",
          "amount": 20,
          "text": "Next attack +20"
        }
      ],
      "voice": "katakuri"
    }
  },
  {
    "id": "kawamatsu",
    "name": "Kawamatsu",
    "rarity": "common",
    "crew": "netherlands",
    "card": {
      "element": "tide",
      "archetype": "guardian",
      "hp": 120,
      "retreat": 2,
      "attacks": [
        {
          "name": "Kappa Guard",
          "cost": 1,
          "damage": 25
        },
        {
          "name": "Sake Slash",
          "cost": 2,
          "damage": 60,
          "effect": "heal",
          "amount": 20,
          "text": "Heal 20 HP"
        }
      ]
    }
  },
  {
    "id": "killer-post-timeskip-render",
    "name": "Killer",
    "rarity": "common",
    "crew": "portugal",
    "card": {
      "element": "blade",
      "archetype": "striker",
      "hp": 100,
      "retreat": 1,
      "attacks": [
        {
          "name": "Rotating Blade",
          "cost": 1,
          "damage": 35
        },
        {
          "name": "Scratch Wave",
          "cost": 2,
          "damage": 80
        }
      ]
    }
  },
  {
    "id": "king-original",
    "name": "King",
    "rarity": "common",
    "crew": "argentina",
    "card": {
      "element": "flame",
      "archetype": "bruiser",
      "hp": 115,
      "retreat": 2,
      "attacks": [
        {
          "name": "Wildfire Wing",
          "cost": 1,
          "damage": 20
        },
        {
          "name": "Flame Lance",
          "cost": 2,
          "damage": 72,
          "effect": "boost",
          "amount": 20,
          "text": "Next attack +20"
        }
      ]
    }
  },
  {
    "id": "kody29-onepiece",
    "name": "Straw Hat Crew",
    "rarity": "common",
    "crew": "spain",
    "card": {
      "element": "beast",
      "archetype": "bruiser",
      "hp": 115,
      "retreat": 2,
      "attacks": [
        {
          "name": "All Hands Rush",
          "cost": 1,
          "damage": 30
        },
        {
          "name": "Crew Combo",
          "cost": 2,
          "damage": 62,
          "effect": "boost",
          "amount": 20,
          "text": "Next attack +20"
        }
      ],
      "voice": "luffy"
    }
  },
  {
    "id": "kyoshiro-one-piece",
    "name": "Kyoshiro",
    "rarity": "common",
    "crew": "spain",
    "card": {
      "element": "blade",
      "archetype": "bruiser",
      "hp": 135,
      "retreat": 2,
      "attacks": [
        {
          "name": "Wave Cut",
          "cost": 1,
          "damage": 25
        },
        {
          "name": "Winter Moon",
          "cost": 2,
          "damage": 67,
          "effect": "boost",
          "amount": 20,
          "text": "Next attack +20"
        }
      ]
    }
  },
  {
    "id": "lkpxy7a4g69ycyntpghhqitipgjf8n76czjuvmnbcpvsqpoy",
    "name": "Xuqphecel Lqg",
    "rarity": "special",
    "crew": "belgium",
    "card": {
      "element": "blade",
      "archetype": "trickster",
      "hp": 120,
      "retreat": 1,
      "attacks": [
        {
          "name": "Iron Slash",
          "cost": 1,
          "damage": 25
        },
        {
          "name": "Flying Slash",
          "cost": 3,
          "damage": 76,
          "effect": "stun",
          "text": "They can’t attack next turn"
        }
      ]
    }
  },
  {
    "id": "loki-anime-concept-art-copy",
    "name": "Loki",
    "rarity": "common",
    "crew": "netherlands",
    "card": {
      "element": "storm",
      "archetype": "bruiser",
      "hp": 105,
      "retreat": 2,
      "attacks": [
        {
          "name": "Chain Swing",
          "cost": 1,
          "damage": 30
        },
        {
          "name": "Sky Breaker",
          "cost": 2,
          "damage": 62,
          "effect": "boost",
          "amount": 20,
          "text": "Next attack +20"
        }
      ]
    }
  },
  {
    "id": "lucci-cp0-1",
    "name": "Rob Lucci",
    "rarity": "common",
    "crew": "spain",
    "card": {
      "element": "beast",
      "archetype": "striker",
      "hp": 110,
      "retreat": 1,
      "attacks": [
        {
          "name": "Shigan",
          "cost": 1,
          "damage": 30
        },
        {
          "name": "Rokuogan",
          "cost": 2,
          "damage": 90
        }
      ]
    }
  },
  {
    "id": "lucci-cp0",
    "name": "Rob Lucci · CP0",
    "rarity": "common",
    "crew": "argentina",
    "card": {
      "element": "beast",
      "archetype": "striker",
      "hp": 110,
      "retreat": 1,
      "attacks": [
        {
          "name": "Shigan",
          "cost": 1,
          "damage": 35
        },
        {
          "name": "Rokuogan",
          "cost": 2,
          "damage": 80
        }
      ]
    }
  },
  {
    "id": "luffygear5",
    "name": "Luffy · Gear 5",
    "rarity": "common",
    "crew": "france",
    "card": {
      "element": "beast",
      "archetype": "striker",
      "hp": 100,
      "retreat": 1,
      "attacks": [
        {
          "name": "Rubber Balloon",
          "cost": 1,
          "damage": 30
        },
        {
          "name": "Bajrang Gun",
          "cost": 2,
          "damage": 85
        }
      ],
      "voice": "luffy"
    }
  },
  {
    "id": "marco-the-phoenix",
    "name": "Marco the Phoenix",
    "rarity": "common",
    "crew": "argentina",
    "card": {
      "element": "flame",
      "archetype": "guardian",
      "hp": 140,
      "retreat": 2,
      "attacks": [
        {
          "name": "Phoenix Brand",
          "cost": 1,
          "damage": 15
        },
        {
          "name": "Blue Flame Rebirth",
          "cost": 2,
          "damage": 60,
          "effect": "heal",
          "amount": 20,
          "text": "Heal 20 HP"
        }
      ]
    }
  },
  {
    "id": "mihawk-render",
    "name": "Mihawk · Hawk Eyes",
    "rarity": "common",
    "crew": "brazil",
    "card": {
      "element": "blade",
      "archetype": "striker",
      "hp": 110,
      "retreat": 1,
      "attacks": [
        {
          "name": "Hawk Slash",
          "cost": 1,
          "damage": 25
        },
        {
          "name": "Black Blade",
          "cost": 2,
          "damage": 85
        }
      ]
    }
  },
  {
    "id": "momong",
    "name": "Kozuki Momonosuke",
    "rarity": "common",
    "crew": "france",
    "card": {
      "element": "beast",
      "archetype": "guardian",
      "hp": 130,
      "retreat": 2,
      "attacks": [
        {
          "name": "Dragon Twister",
          "cost": 1,
          "damage": 15
        },
        {
          "name": "Flame Cloud",
          "cost": 2,
          "damage": 50,
          "effect": "heal",
          "amount": 20,
          "text": "Heal 20 HP"
        }
      ]
    }
  },
  {
    "id": "monkey-d-luffy-gear-4-render-11563147961xnnsgtzk",
    "name": "Luffy · Gear 4",
    "rarity": "common",
    "crew": "spain",
    "card": {
      "element": "beast",
      "archetype": "bruiser",
      "hp": 125,
      "retreat": 2,
      "attacks": [
        {
          "name": "Kong Gun",
          "cost": 1,
          "damage": 25
        },
        {
          "name": "Leo Bazooka",
          "cost": 2,
          "damage": 62,
          "effect": "boost",
          "amount": 20,
          "text": "Next attack +20"
        }
      ],
      "voice": "luffy"
    }
  },
  {
    "id": "monkey-d-luffy-one-piece-monkey-d-luffy-wallpape",
    "name": "Monkey D. Luffy",
    "rarity": "special",
    "crew": "brazil",
    "card": {
      "element": "beast",
      "archetype": "bruiser",
      "hp": 125,
      "retreat": 2,
      "attacks": [
        {
          "name": "Gum-Gum Pistol",
          "cost": 1,
          "damage": 35
        },
        {
          "name": "Gum-Gum Red Roc",
          "cost": 3,
          "damage": 82,
          "effect": "boost",
          "amount": 20,
          "text": "Next attack +20"
        }
      ],
      "voice": "luffy"
    }
  },
  {
    "id": "nami-elbaph-official-by-monkeyoflife-dktbt1e-ful",
    "name": "Nami Elbaph Official Monkeyo",
    "rarity": "common",
    "crew": "germany",
    "card": {
      "element": "storm",
      "archetype": "trickster",
      "hp": 110,
      "retreat": 1,
      "attacks": [
        {
          "name": "Thunderbolt Tempo",
          "cost": 1,
          "damage": 30
        },
        {
          "name": "Zeus Breeze Tempo",
          "cost": 2,
          "damage": 61,
          "effect": "stun",
          "text": "They can’t attack next turn"
        }
      ],
      "voice": "nami"
    }
  },
  {
    "id": "nami-onigashima-official-by-monkeyoflife-dje6rrx",
    "name": "Nami · Onigashima",
    "rarity": "common",
    "crew": "spain",
    "card": {
      "element": "storm",
      "archetype": "trickster",
      "hp": 90,
      "retreat": 1,
      "attacks": [
        {
          "name": "Thunderbolt Tempo",
          "cost": 1,
          "damage": 30
        },
        {
          "name": "Zeus Breeze Tempo",
          "cost": 2,
          "damage": 56,
          "effect": "stun",
          "text": "They can’t attack next turn"
        }
      ],
      "voice": "nami"
    }
  },
  {
    "id": "new-shogun-kozuki-momonosuke-by-robirh-df6kq3l-f",
    "name": "Shogun Momonosuke",
    "rarity": "common",
    "crew": "portugal",
    "card": {
      "element": "beast",
      "archetype": "guardian",
      "hp": 140,
      "retreat": 2,
      "attacks": [
        {
          "name": "Dragon Twister",
          "cost": 1,
          "damage": 25
        },
        {
          "name": "Flame Cloud",
          "cost": 2,
          "damage": 50,
          "effect": "heal",
          "amount": 20,
          "text": "Heal 20 HP"
        }
      ]
    }
  },
  {
    "id": "o-lin-jumputi",
    "name": "Charlotte Linlin",
    "rarity": "common",
    "crew": "portugal",
    "card": {
      "element": "spirit",
      "archetype": "guardian",
      "hp": 130,
      "retreat": 2,
      "attacks": [
        {
          "name": "Prometheus Blaze",
          "cost": 1,
          "damage": 15
        },
        {
          "name": "Ikoku Sovereignty",
          "cost": 2,
          "damage": 50,
          "effect": "heal",
          "amount": 20,
          "text": "Heal 20 HP"
        }
      ],
      "voice": "bigmom"
    }
  },
  {
    "id": "one-piece-monkey-d-luffy-512x512",
    "name": "Luffy · Straw Hat",
    "rarity": "common",
    "crew": "england",
    "card": {
      "element": "beast",
      "archetype": "bruiser",
      "hp": 125,
      "retreat": 2,
      "attacks": [
        {
          "name": "Gum-Gum Pistol",
          "cost": 1,
          "damage": 20
        },
        {
          "name": "Gum-Gum Red Roc",
          "cost": 2,
          "damage": 67,
          "effect": "boost",
          "amount": 20,
          "text": "Next attack +20"
        }
      ],
      "voice": "luffy"
    }
  },
  {
    "id": "perona-render-01",
    "name": "Perona",
    "rarity": "common",
    "crew": "england",
    "card": {
      "element": "spirit",
      "archetype": "trickster",
      "hp": 110,
      "retreat": 1,
      "attacks": [
        {
          "name": "Ghost Rap",
          "cost": 1,
          "damage": 25
        },
        {
          "name": "Negative Hollow",
          "cost": 2,
          "damage": 56,
          "effect": "stun",
          "text": "They can’t attack next turn"
        }
      ]
    }
  },
  {
    "id": "pica-render",
    "name": "Pica",
    "rarity": "common",
    "crew": "england",
    "card": {
      "element": "beast",
      "archetype": "guardian",
      "hp": 150,
      "retreat": 2,
      "attacks": [
        {
          "name": "Stone Fist",
          "cost": 1,
          "damage": 20
        },
        {
          "name": "Colossus Crush",
          "cost": 2,
          "damage": 50,
          "effect": "heal",
          "amount": 20,
          "text": "Heal 20 HP"
        }
      ]
    }
  },
  {
    "id": "png-clipart-boa-hancock-nico-robin-one-piece-mon",
    "name": "Boa Hancock & Nico Robin",
    "rarity": "common",
    "crew": "portugal",
    "card": {
      "element": "spirit",
      "archetype": "trickster",
      "hp": 90,
      "retreat": 1,
      "attacks": [
        {
          "name": "Slave Arrow",
          "cost": 1,
          "damage": 20
        },
        {
          "name": "Perfume Femur",
          "cost": 2,
          "damage": 56,
          "effect": "stun",
          "text": "They can’t attack next turn"
        }
      ]
    }
  },
  {
    "id": "png-clipart-monkey-d-luffy-monkey-d-garp-gol-d-r",
    "name": "Luffy, Garp & Roger",
    "rarity": "common",
    "crew": "argentina",
    "card": {
      "element": "beast",
      "archetype": "bruiser",
      "hp": 135,
      "retreat": 2,
      "attacks": [
        {
          "name": "Gum-Gum Pistol",
          "cost": 1,
          "damage": 20
        },
        {
          "name": "Gum-Gum Red Roc",
          "cost": 2,
          "damage": 62,
          "effect": "boost",
          "amount": 20,
          "text": "Next attack +20"
        }
      ],
      "voice": "luffy"
    }
  },
  {
    "id": "poll-bartolomeo-or-cavendish-who-do-you-prefer-i",
    "name": "Poll Bartolomeo Or Cavendish",
    "rarity": "special",
    "crew": "portugal",
    "card": {
      "element": "spirit",
      "archetype": "guardian",
      "hp": 150,
      "retreat": 2,
      "attacks": [
        {
          "name": "Barrier",
          "cost": 1,
          "damage": 20
        },
        {
          "name": "Barrier Bulls",
          "cost": 3,
          "damage": 60,
          "effect": "heal",
          "amount": 20,
          "text": "Heal 20 HP"
        }
      ]
    }
  },
  {
    "id": "queen-original",
    "name": "Queen",
    "rarity": "common",
    "crew": "france",
    "card": {
      "element": "beast",
      "archetype": "trickster",
      "hp": 110,
      "retreat": 1,
      "attacks": [
        {
          "name": "Brachio Bomber",
          "cost": 1,
          "damage": 25
        },
        {
          "name": "Plague Rounds",
          "cost": 2,
          "damage": 61,
          "effect": "stun",
          "text": "They can’t attack next turn"
        }
      ]
    }
  },
  {
    "id": "raizo-anime",
    "name": "Raizo",
    "rarity": "common",
    "crew": "england",
    "card": {
      "element": "spirit",
      "archetype": "trickster",
      "hp": 100,
      "retreat": 1,
      "attacks": [
        {
          "name": "Scroll Trap",
          "cost": 1,
          "damage": 20
        },
        {
          "name": "Ninja Art: Flame",
          "cost": 2,
          "damage": 56,
          "effect": "stun",
          "text": "They can’t attack next turn"
        }
      ]
    }
  },
  {
    "id": "rob-lucci-by-orochimarusama1-by-staxkiller-d8rj4",
    "name": "Rob Lucci · Leopard",
    "rarity": "common",
    "crew": "portugal",
    "card": {
      "element": "beast",
      "archetype": "striker",
      "hp": 100,
      "retreat": 1,
      "attacks": [
        {
          "name": "Shigan",
          "cost": 1,
          "damage": 25
        },
        {
          "name": "Rokuogan",
          "cost": 2,
          "damage": 85
        }
      ]
    }
  },
  {
    "id": "robin-elbaph-official-by-monkeyoflife-dktc8i6-fu",
    "name": "Robin Elbaph Official Monkey",
    "rarity": "common",
    "crew": "spain",
    "card": {
      "element": "spirit",
      "archetype": "trickster",
      "hp": 120,
      "retreat": 1,
      "attacks": [
        {
          "name": "Mil Fleurs",
          "cost": 1,
          "damage": 25
        },
        {
          "name": "Gigante Fleur",
          "cost": 2,
          "damage": 66,
          "effect": "stun",
          "text": "They can’t attack next turn"
        }
      ],
      "voice": "robin"
    }
  },
  {
    "id": "robin-render",
    "name": "Nico Robin",
    "rarity": "common",
    "crew": "netherlands",
    "card": {
      "element": "spirit",
      "archetype": "trickster",
      "hp": 90,
      "retreat": 1,
      "attacks": [
        {
          "name": "Mil Fleurs",
          "cost": 1,
          "damage": 25
        },
        {
          "name": "Gigante Fleur",
          "cost": 2,
          "damage": 66,
          "effect": "stun",
          "text": "They can’t attack next turn"
        }
      ],
      "voice": "robin"
    }
  },
  {
    "id": "roronoa-zoro",
    "name": "Roronoa Zoro",
    "rarity": "common",
    "crew": "england",
    "card": {
      "element": "blade",
      "archetype": "striker",
      "hp": 80,
      "retreat": 1,
      "attacks": [
        {
          "name": "Oni Giri",
          "cost": 1,
          "damage": 25
        },
        {
          "name": "Three Sword Style: Purgatory",
          "cost": 2,
          "damage": 90
        }
      ],
      "voice": "zoro"
    }
  },
  {
    "id": "roronoa-zoro-png-clipart",
    "name": "Zoro · Three Swords",
    "rarity": "special",
    "crew": "portugal",
    "card": {
      "element": "blade",
      "archetype": "striker",
      "hp": 120,
      "retreat": 1,
      "attacks": [
        {
          "name": "Oni Giri",
          "cost": 1,
          "damage": 40
        },
        {
          "name": "Three Sword Style: Purgatory",
          "cost": 3,
          "damage": 95
        }
      ],
      "voice": "zoro"
    }
  },
  {
    "id": "ryokugyu-vs-luffy",
    "name": "Ryokugyu Vs Luffy",
    "rarity": "common",
    "crew": "belgium",
    "card": {
      "element": "beast",
      "archetype": "guardian",
      "hp": 120,
      "retreat": 2,
      "attacks": [
        {
          "name": "Forest Bind",
          "cost": 1,
          "damage": 20
        },
        {
          "name": "Drain Forest",
          "cost": 2,
          "damage": 50,
          "effect": "heal",
          "amount": 20,
          "text": "Heal 20 HP"
        }
      ]
    }
  },
  {
    "id": "sabo-s-devil-fruit",
    "name": "Sabo Devil Fruit",
    "rarity": "common",
    "crew": "netherlands",
    "card": {
      "element": "flame",
      "archetype": "bruiser",
      "hp": 125,
      "retreat": 2,
      "attacks": [
        {
          "name": "Dragon Claw",
          "cost": 1,
          "damage": 25
        },
        {
          "name": "Dragon's Breath",
          "cost": 2,
          "damage": 67,
          "effect": "boost",
          "amount": 20,
          "text": "Next attack +20"
        }
      ]
    }
  },
  {
    "id": "sanji-sanji-new-world-full-body-115633029592ajtk",
    "name": "Vinsmoke Sanji",
    "rarity": "common",
    "crew": "germany",
    "card": {
      "element": "flame",
      "archetype": "striker",
      "hp": 80,
      "retreat": 1,
      "attacks": [
        {
          "name": "Sky Walk Kick",
          "cost": 1,
          "damage": 35
        },
        {
          "name": "Diable Jambe",
          "cost": 2,
          "damage": 85
        }
      ],
      "voice": "sanji"
    }
  },
  {
    "id": "shanks",
    "name": "Red-Haired Shanks",
    "rarity": "common",
    "crew": "belgium",
    "card": {
      "element": "blade",
      "archetype": "bruiser",
      "hp": 105,
      "retreat": 2,
      "attacks": [
        {
          "name": "Conqueror's Glare",
          "cost": 1,
          "damage": 20
        },
        {
          "name": "Divine Departure",
          "cost": 2,
          "damage": 72,
          "effect": "boost",
          "amount": 20,
          "text": "Next attack +20"
        }
      ],
      "voice": "shanks"
    }
  },
  {
    "id": "shimotsuki-ryumamonsters-103-mercies-dragon-damn",
    "name": "Shimotsuki Ryumamonsters Mer",
    "rarity": "common",
    "crew": "germany",
    "card": {
      "element": "blade",
      "archetype": "striker",
      "hp": 100,
      "retreat": 1,
      "attacks": [
        {
          "name": "Gavotte Bond en Avant",
          "cost": 1,
          "damage": 25
        },
        {
          "name": "Dragon Slayer",
          "cost": 2,
          "damage": 80
        }
      ]
    }
  },
  {
    "id": "tony-tony-chopper-brown-animal-character-wallpap",
    "name": "Tony Tony Chopper Brown Anim",
    "rarity": "special",
    "crew": "spain",
    "card": {
      "element": "beast",
      "archetype": "guardian",
      "hp": 170,
      "retreat": 2,
      "attacks": [
        {
          "name": "Kung Fu Point",
          "cost": 1,
          "damage": 25
        },
        {
          "name": "Monster Point",
          "cost": 3,
          "damage": 65,
          "effect": "heal",
          "amount": 20,
          "text": "Heal 20 HP"
        }
      ],
      "voice": "chopper"
    }
  },
  {
    "id": "top-20-strongest-one-piece-characters-powerscali",
    "name": "Legends of the Sea",
    "rarity": "common",
    "crew": "england",
    "card": {
      "element": "tide",
      "archetype": "guardian",
      "hp": 130,
      "retreat": 2,
      "attacks": [
        {
          "name": "Old Tide",
          "cost": 1,
          "damage": 25
        },
        {
          "name": "Legend's Wave",
          "cost": 2,
          "damage": 50,
          "effect": "heal",
          "amount": 20,
          "text": "Heal 20 HP"
        }
      ]
    }
  },
  {
    "id": "urouge",
    "name": "Urouge",
    "rarity": "common",
    "crew": "france",
    "card": {
      "element": "beast",
      "archetype": "bruiser",
      "hp": 135,
      "retreat": 2,
      "attacks": [
        {
          "name": "Sky Grudge",
          "cost": 1,
          "damage": 20
        },
        {
          "name": "Damage Return",
          "cost": 2,
          "damage": 62,
          "effect": "boost",
          "amount": 20,
          "text": "Next attack +20"
        }
      ]
    }
  },
  {
    "id": "usopp-one-piece-usopp-wallpaper-png-clipart",
    "name": "Sogeking",
    "rarity": "special",
    "crew": "france",
    "card": {
      "element": "spirit",
      "archetype": "trickster",
      "hp": 110,
      "retreat": 1,
      "attacks": [
        {
          "name": "Sniper Shot",
          "cost": 1,
          "damage": 25
        },
        {
          "name": "Firebird Star",
          "cost": 3,
          "damage": 76,
          "effect": "stun",
          "text": "They can’t attack next turn"
        }
      ],
      "voice": "usopp"
    }
  },
  {
    "id": "uta-one-piece",
    "name": "Uta",
    "rarity": "common",
    "crew": "england",
    "card": {
      "element": "spirit",
      "archetype": "trickster",
      "hp": 100,
      "retreat": 1,
      "attacks": [
        {
          "name": "Sing for Me",
          "cost": 1,
          "damage": 25
        },
        {
          "name": "Tot Musica",
          "cost": 2,
          "damage": 61,
          "effect": "stun",
          "text": "They can’t attack next turn"
        }
      ]
    }
  },
  {
    "id": "vegapunkrender",
    "name": "Vegapunkrender",
    "rarity": "common",
    "crew": "netherlands",
    "card": {
      "element": "storm",
      "archetype": "guardian",
      "hp": 120,
      "retreat": 2,
      "attacks": [
        {
          "name": "Punk Ray",
          "cost": 1,
          "damage": 25
        },
        {
          "name": "Satellite Barrage",
          "cost": 2,
          "damage": 55,
          "effect": "heal",
          "amount": 20,
          "text": "Heal 20 HP"
        }
      ]
    }
  },
  {
    "id": "vinsmoke-sanji-one-piece-treasure-cruise-monkey-",
    "name": "Sanji · Black Leg",
    "rarity": "special",
    "crew": "belgium",
    "card": {
      "element": "flame",
      "archetype": "striker",
      "hp": 120,
      "retreat": 1,
      "attacks": [
        {
          "name": "Diable Jambe",
          "cost": 1,
          "damage": 40
        },
        {
          "name": "Hell Memories",
          "cost": 3,
          "damage": 90
        }
      ],
      "voice": "sanji"
    }
  },
  {
    "id": "what-do-you-think-made-rocks-d-xebec-so-strong-v",
    "name": "What Do You Think Made Rocks",
    "rarity": "common",
    "crew": "germany",
    "card": {
      "element": "storm",
      "archetype": "guardian",
      "hp": 140,
      "retreat": 2,
      "attacks": [
        {
          "name": "Static Snap",
          "cost": 1,
          "damage": 25
        },
        {
          "name": "Sky Judgment",
          "cost": 2,
          "damage": 55,
          "effect": "heal",
          "amount": 20,
          "text": "Heal 20 HP"
        }
      ]
    }
  },
  {
    "id": "yasopp-render",
    "name": "Yasopp",
    "rarity": "common",
    "crew": "netherlands",
    "card": {
      "element": "storm",
      "archetype": "striker",
      "hp": 100,
      "retreat": 1,
      "attacks": [
        {
          "name": "Long Shot",
          "cost": 1,
          "damage": 35
        },
        {
          "name": "Thousand Shots",
          "cost": 2,
          "damage": 80
        }
      ]
    }
  },
  {
    "id": "zombieryuma-original",
    "name": "Zombieryuma",
    "rarity": "common",
    "crew": "france",
    "card": {
      "element": "blade",
      "archetype": "striker",
      "hp": 110,
      "retreat": 1,
      "attacks": [
        {
          "name": "Gavotte Bond en Avant",
          "cost": 1,
          "damage": 30
        },
        {
          "name": "Dragon Slayer",
          "cost": 2,
          "damage": 90
        }
      ]
    }
  }
]
