// Keeps public/backgrounds/ in shape:
//  1. compresses every image in place (max width 1080, quality ~72) — filenames
//     never change, because owned backgrounds are stored in Firestore by filename
//  2. regenerates src/logic/backgroundCatalog.generated.ts so any file dropped
//     into the folder shows up in the Store automatically
// Runs on `npm run backgrounds`, and before every dev/build via pre-scripts.
import { readdir, readFile, writeFile, stat } from 'node:fs/promises'
import path from 'node:path'
import sharp from 'sharp'

const DIR = new URL('../public/backgrounds/', import.meta.url).pathname
const OUT = new URL('../src/logic/backgroundCatalog.generated.ts', import.meta.url).pathname
const MAX_WIDTH = 810 // phone-only app capped at 480 CSS px; ~2x retina is plenty behind the dark tint
const QUALITY = 65
const BUDGET = 180 * 1024 // above this, step quality down until it fits (floor 40)

const EXT = { '.jpg': 'jpeg', '.jpeg': 'jpeg', '.png': 'png', '.webp': 'webp' }

const files = (await readdir(DIR))
  .filter((f) => EXT[path.extname(f).toLowerCase()])
  .sort((a, b) => a.localeCompare(b, 'en', { numeric: true }))

let saved = 0
for (const file of files) {
  const full = path.join(DIR, file)
  const before = (await stat(full)).size
  const format = EXT[path.extname(file).toLowerCase()]
  const img = sharp(await readFile(full)).rotate().resize({ width: MAX_WIDTH, withoutEnlargement: true })
  const encode = (quality) =>
    format === 'jpeg'
      ? img.jpeg({ quality, mozjpeg: true }).toBuffer()
      : format === 'webp'
        ? img.webp({ quality }).toBuffer()
        : img.png({ compressionLevel: 9, palette: true }).toBuffer()
  let quality = QUALITY
  let out = await encode(quality)
  while (out.length > BUDGET && quality > 40 && format !== 'png') {
    quality -= 10
    out = await encode(quality)
  }
  // only rewrite on a real win (≥10%) so repeated runs don't re-encode forever
  if (out.length < before * 0.9) {
    await writeFile(full, out)
    saved += before - out.length
    console.log(`  ${file}: ${(before / 1024).toFixed(0)}kb → ${(out.length / 1024).toFixed(0)}kb`)
  }
}

const ts = `// AUTO-GENERATED by scripts/backgrounds.mjs — do not edit.
// Drop images into public/backgrounds/ and run \`npm run backgrounds\` (also runs before dev/build).
export const BACKGROUND_CATALOG = ${JSON.stringify(files, null, 2)}
`
await writeFile(OUT, ts)
console.log(`${files.length} backgrounds in catalog${saved ? `, saved ${(saved / 1024).toFixed(0)}kb` : ''}`)
