// Builds src/logic/optcgCatalog.generated.ts — every One Piece TCG card the
// deckbuilder and the engine can see.
//
// Two sources, merged:
//   scripts/data/optcg-official.json  the publisher's own card list (category,
//     Life, attribute, power, cost, counter, colors, types, effect) — scraped
//     by `npm run optcg:scrape`, which is the only thing that touches the net.
//   scripts/data/optcg-cards.csv      the downloaded dump: art variants and the
//     ban list, which the official pages don't spell out.
//
// IMAGES ARE NEVER STORED HERE. The official image host answers with
// `Cross-Origin-Resource-Policy: same-site`, so a browser refuses to paint its
// PNGs on our origin — an <img src> to it silently fails. Two public mirrors
// send no such header, so every card carries a primary and a fallback URL and
// the card component swaps on error. Nothing lands in public/.
import { readFile, writeFile } from 'node:fs/promises'

const OFFICIAL = new URL('./data/optcg-official.json', import.meta.url).pathname
const CSV = new URL('./data/optcg-cards.csv', import.meta.url).pathname
const OUT = new URL('../src/logic/optcgCatalog.generated.ts', import.meta.url).pathname

/** Set folder in the mirror's tree: `OP01-006` → `OP01`, `P-001` → `P`. */
const setOf = (code) => code.slice(0, code.lastIndexOf('-'))

// --- the CSV (art variants + bans) -------------------------------------------

/** Minimal RFC-4180 reader: the dump quotes effect text containing commas. */
function parseCsv(text) {
  const rows = []
  let row = []
  let cell = ''
  let quoted = false
  for (let i = 0; i < text.length; i++) {
    const c = text[i]
    if (quoted) {
      if (c === '"') {
        if (text[i + 1] === '"') { cell += '"'; i++ } else quoted = false
      } else cell += c
    } else if (c === '"') quoted = true
    else if (c === ',') { row.push(cell); cell = '' }
    else if (c === '\n') { row.push(cell); rows.push(row); row = []; cell = '' }
    else if (c !== '\r') cell += c
  }
  if (cell || row.length) { row.push(cell); rows.push(row) }
  const head = rows.shift()
  return rows.filter((r) => r.length === head.length).map((r) => Object.fromEntries(head.map((h, i) => [h, r[i]])))
}

const csv = parseCsv(await readFile(CSV, 'utf8'))
const banned = new Set(csv.filter((r) => r.card_banned === '1').map((r) => r.card_code))
const arts = new Map() // code → count of distinct arts, base included
for (const r of csv) {
  const n = Number(r.card_art_variant) || 0
  arts.set(r.card_code, Math.max(arts.get(r.card_code) ?? 0, n))
}

// --- the official list --------------------------------------------------------

const official = JSON.parse(await readFile(OFFICIAL, 'utf8'))

const num = (v) => {
  const n = parseInt(String(v).replace(/[^0-9]/g, ''), 10)
  return Number.isFinite(n) ? n : 0
}

/** "[Trigger] …" is printed at the end of the effect; the engine wants it apart. */
function splitTrigger(effect) {
  const i = effect.indexOf('[Trigger]')
  if (i < 0) return [effect.trim(), '']
  return [effect.slice(0, i).trim(), effect.slice(i).trim()]
}

const CATEGORY = { LEADER: 'leader', CHARACTER: 'character', EVENT: 'event', STAGE: 'stage' }

const cards = []
for (const c of Object.values(official)) {
  const kind = CATEGORY[c.category]
  if (!kind) continue
  const [effect, trigger] = splitTrigger(c.effect)
  const colors = c.color.split('/').map((s) => s.trim().toLowerCase()).filter(Boolean)
  cards.push({
    code: c.code,
    name: c.name,
    kind,
    colors,
    types: c.types.split('/').map((s) => s.trim()).filter(Boolean),
    // A Leader's "cost" box is its Life; everything else pays a cost.
    cost: kind === 'leader' ? 0 : num(c.cost),
    life: kind === 'leader' ? num(c.cost) : 0,
    power: num(c.power),
    counter: num(c.counter),
    attribute: c.attribute || '',
    rarity: c.rarity,
    effect,
    trigger,
    arts: (arts.get(c.code) ?? 0) + 1,
    banned: banned.has(c.code),
  })
}
cards.sort((a, b) => a.code.localeCompare(b.code))

const q = (s) => JSON.stringify(s)
const body = cards
  .map((c) => {
    const bits = [
      `code:${q(c.code)}`,
      `name:${q(c.name)}`,
      `kind:${q(c.kind)}`,
      `colors:[${c.colors.map(q).join(',')}]`,
      `types:[${c.types.map(q).join(',')}]`,
      `cost:${c.cost}`,
      `power:${c.power}`,
      `counter:${c.counter}`,
      `attribute:${q(c.attribute)}`,
      `rarity:${q(c.rarity)}`,
      `effect:${q(c.effect)}`,
      `trigger:${q(c.trigger)}`,
      `arts:${c.arts}`,
    ]
    if (c.life) bits.push(`life:${c.life}`)
    if (c.banned) bits.push('banned:true')
    return `  { ${bits.join(', ')} },`
  })
  .join('\n')

const sets = [...new Set(cards.map((c) => setOf(c.code)))].sort()

const file = `// GENERATED by scripts/optcg-catalog.mjs — do not edit by hand.
// ${cards.length} One Piece TCG cards, from the official card list.
// Regenerate with \`npm run optcg:cards\` (and \`npm run optcg:scrape\` first to
// re-harvest the source).
import type { OptcgCard } from './optcg'

// Imported through logic/optcgCards.ts, never directly: that module is what
// registers these cards with the engine, and keeping this file out of the main
// bundle is the whole reason it exists.

/** Every set folder present, newest first in the deckbuilder's filter. */
export const OPTCG_SETS: string[] = [${sets.map(q).join(', ')}]

export const OPTCG_CARDS: OptcgCard[] = [
${body}
]
`
await writeFile(OUT, file)
console.log(`${cards.length} cards → ${OUT}`)
